<a href="https://colab.research.google.com/github/Esaipriya/AISECT-ML/blob/main/ML_preprocessing_RFE_selection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
pd.set_option('display.max_columns', None)

In [2]:
dataset = pd.read_csv('/content/kidney_disease.csv')

In [3]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 26 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              400 non-null    int64
 1   age             391 non-null    float64
 2   bp              388 non-null    float64
 3   sg              353 non-null    float64
 4   al              354 non-null    float64
 5   su              351 non-null    float64
 6   rbc             248 non-null    object
 7   pc              335 non-null    object
 8   pcc             396 non-null    object
 9   ba              396 non-null    object
 10  bgr             356 non-null    float64
 11  bu              381 non-null    float64
 12  sc              383 non-null    float64
 13  sod             313 non-null    float64
 14  pot             312 non-null    float64
 15  hemo            348 non-null    float64
 16  pcv             330 non-null    object
 17  wc              295 non-null    object
 18  rc              270 non-null    object
 19  htn             398 non-null    object
 20  dm              398 non-null    object
 21  cad             398 non-null    object
 22  appet           399 non-null    object
 23  pe              399 non-null    object
 24  ane             399 non-null    object
 25  classification  400 non-null    object
dtypes: float64(11), int64(1), object(14)
memory usage: 81.4+ KB

In [4]:
dataset.head()

,id,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,bu,sc,sod,pot,hemo,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,0,48.0,80.0,1.020,1.0,0.0,NaN,normal,notpresent,notpresent,121.0,36.0,1.2,NaN,NaN,15.4,44,7800,5.2,yes,yes,no,good,no,no,ckd
1,1,7.0,50.0,1.020,4.0,0.0,NaN,normal,notpresent,notpresent,NaN,18.0,0.8,NaN,NaN,11.3,38,6000,NaN,no,no,no,good,no,no,ckd
2,2,62.0,80.0,1.010,2.0,3.0,normal,normal,notpresent,notpresent,423.0,53.0,1.8,NaN,NaN,9.6,31,7500,NaN,no,yes,no,poor,no,yes,ckd
3,3,48.0,70.0,1.005,4.0,0.0,normal,abnormal,present,notpresent,117.0,56.0,3.8,111.0,2.5,11.2,32,6700,3.9,yes,no,no,poor,yes,yes,ckd
4,4,51.0,80.0,1.010,2.0,0.0,normal,normal,notpresent,notpresent,106.0,26.0,1.4,NaN,NaN,11.6,35,7300,4.6,no,no,no,good,no,no,ckd

In [5]:
dataset.columns

Index(['id', 'age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr',
       'bu', 'sc', 'sod', 'pot', 'hemo', 'pcv', 'wc', 'rc', 'htn', 'dm', 'cad',
       'appet', 'pe', 'ane', 'classification'],
      dtype='object')

In [6]:
dataset[["al"]].value_counts()

al
0.0    199
1.0     44
2.0     43
3.0     43
4.0     24
5.0      1
Name: count, dtype: int64

In [7]:
dataset[["al"]].isnull().sum()

al    46
dtype: int64

In [8]:
from sklearn.preprocessing import StandardScaler
# Scale features before imputation
scaler = StandardScaler()
data_scaled = scaler.fit_transform(dataset[["al"]])

In [9]:
# Step 2: Apply KNN Imputer
from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=3)
data_imputed = imputer.fit_transform(data_scaled)

In [10]:
# Step 3: Inverse scaling back to original scale
data_imputed = scaler.inverse_transform(data_imputed)

In [11]:
data_imputed

array([[1.        ],
       [4.        ],
       [2.        ],
       [4.        ],
       [2.        ],
       [3.        ],
       [0.        ],
       [2.        ],
       [3.        ],
       [2.        ],
       [2.        ],
       [3.        ],
       [3.        ],
       [1.01694915],
       [3.        ],
       [3.        ],
       [2.        ],
       [1.01694915],
       [0.        ],
       [1.        ],
       [2.        ],
       [1.01694915],
       [4.        ],
       [0.        ],
       [4.        ],
       [0.        ],
       [0.        ],
       [3.        ],
       [1.        ],
       [1.        ],
       [1.01694915],
       [3.        ],
       [1.        ],
       [2.        ],
       [1.        ],
       [2.        ],
       [1.        ],
       [1.01694915],
       [3.        ],
       [2.        ],
       [2.        ],
       [0.        ],
       [0.        ],
       [1.        ],
       [3.        ],
       [3.        ],
       [0.        ],
       [3.        ],
       [0.        ],
       [2.        ],
       [1.01694915],
       [3.        ],
       [0.        ],
       [0.        ],
       [2.        ],
       [3.        ],
       [3.        ],
       [1.01694915],
       [2.        ],
       [1.01694915],
       [1.        ],
       [1.        ],
       [3.        ],
       [1.        ],
       [0.        ],
       [1.        ],
       [2.        ],
       [3.        ],
       [2.        ],
       [0.        ],
       [0.        ],
       [1.        ],
       [3.        ],
       [2.        ],
       [2.        ],
       [1.        ],
       [4.        ],
       [1.        ],
       [1.01694915],
       [1.        ],
       [0.        ],
       [1.01694915],
       [1.01694915],
       [1.        ],
       [3.        ],
       [2.        ],
       [1.01694915],
       [1.        ],
       [4.        ],
       [0.        ],
       [2.        ],
       [4.        ],
       [3.        ],
       [3.        ],
       [0.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.01694915],
       [0.        ],
       [4.        ],
       [2.        ],
       [0.        ],
       [2.        ],
       [1.01694915],
       [0.        ],
       [1.01694915],
       [1.        ],
       [0.        ],
       [1.01694915],
       [0.        ],
       [3.        ],
       [3.        ],
       [0.        ],
       [3.        ],
       [0.        ],
       [4.        ],
       [0.        ],
       [3.        ],
       [0.        ],
       [1.        ],
       [3.        ],
       [1.01694915],
       [2.        ],
       [0.        ],
       [1.01694915],
       [0.        ],
       [4.        ],
       [4.        ],
       [1.        ],
       [2.        ],
       [0.        ],
       [1.01694915],
       [4.        ],
       [1.01694915],
       [0.        ],
       [1.01694915],
       [2.        ],
       [1.        ],
       [2.        ],
       [0.        ],
       [1.        ],
       [1.01694915],
       [1.        ],
       [2.        ],
       [5.        ],
       [1.        ],
       [3.        ],
       [1.01694915],
       [1.        ],
       [3.        ],
       [1.01694915],
       [0.        ],
       [2.        ],
       [4.        ],
       [3.        ],
       [2.        ],
       [3.        ],
       [3.        ],
       [1.        ],
       [1.01694915],
       [3.        ],
       [1.01694915],
       [0.        ],
       [0.        ],
       [0.        ],
       [1.01694915],
       [0.        ],
       [4.        ],
       [0.        ],
       [2.        ],
       [3.        ],
       [1.        ],
       [1.        ],
       [1.01694915],
       [0.        ],
       [4.        ],
       [2.        ],
       [2.        ],
       [2.        ],
       [1.        ],
       [2.        ],
       [0.        ],
       [0.        ],
       [3.        ],
       [1.        ],
       [4.        ],
       [2.        ],
       [1.01694915],
       [4.        ],
       [4.        ],
       [3.        ],
       [0.        ],
       [1.        ],
       [2.        ],
       [2.        ],
       [3.        ],
       [1.01694915],
       [4.        ],
       [0.        ],
       [1.        ],
       [1.01694915],
       [1.01694915],
       [1.01694915],
       [4.        ],
       [1.01694915],
       [1.        ],
       [0.        ],
       [1.01694915],
       [0.        ],
       [4.        ],
       [0.        ],
       [3.        ],
       [3.        ],
       [0.        ],
       [3.        ],
       [0.        ],
       [1.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [1.        ],
       [1.01694915],
       [0.        ],
       [0.        ],
       [3.        ],
       [4.        ],
       [0.        ],
       [1.01694915],
       [3.        ],
       [2.        ],
       [1.01694915],
       [1.        ],
       [2.        ],
       [0.        ],
       [2.        ],
       [1.01694915],
       [2.        ],
       [1.01694915],
       [2.        ],
       [1.        ],
       [1.        ],
       [4.        ],
       [2.        ],
       [3.        ],
       [1.01694915],
       [3.        ],
       [1.        ],
       [1.        ],
       [4.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [1.01694915],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [1.01694915],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [1.01694915],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [1.01694915],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [1.01694915],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ]])

In [12]:
# Step 4: Convert back to DataFrame
imputed_df = pd.DataFrame(data_imputed, columns=["al"])

In [13]:
imputed_df

      al
0    1.0
1    4.0
2    2.0
3    4.0
4    2.0
..   ...
395  0.0
396  0.0
397  0.0
398  0.0
399  0.0

[400 rows x 1 columns]

In [14]:
imputed_df.value_counts()

al
0.000000    199
1.016949     46
1.000000     44
2.000000     43
3.000000     43
4.000000     24
5.000000      1
Name: count, dtype: int64

In [15]:
import numpy as np

In [16]:
# Round & clip 'al'
dataset[["al"]] = np.clip(np.round(imputed_df), 0, 5).astype(int)

In [17]:
dataset[["al"]].value_counts()

al
0     199
1      90
2      43
3      43
4      24
5       1
Name: count, dtype: int64

In [18]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 26 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              400 non-null    int64
 1   age             391 non-null    float64
 2   bp              388 non-null    float64
 3   sg              353 non-null    float64
 4   al              400 non-null    int64
 5   su              351 non-null    float64
 6   rbc             248 non-null    object
 7   pc              335 non-null    object
 8   pcc             396 non-null    object
 9   ba              396 non-null    object
 10  bgr             356 non-null    float64
 11  bu              381 non-null    float64
 12  sc              383 non-null    float64
 13  sod             313 non-null    float64
 14  pot             312 non-null    float64
 15  hemo            348 non-null    float64
 16  pcv             330 non-null    object
 17  wc              295 non-null    object
 18  rc              270 non-null    object
 19  htn             398 non-null    object
 20  dm              398 non-null    object
 21  cad             398 non-null    object
 22  appet           399 non-null    object
 23  pe              399 non-null    object
 24  ane             399 non-null    object
 25  classification  400 non-null    object
dtypes: float64(10), int64(2), object(14)
memory usage: 81.4+ KB

In [19]:
from sklearn.preprocessing import StandardScaler
# Scale features before imputation
scaler = StandardScaler()
data_scaled = scaler.fit_transform(dataset[["age"]])

In [20]:
data_scaled

array([[-0.20313902],
       [-2.59412412],
       [ 0.61329491],
       [-0.20313902],
       [-0.0281889 ],
       [ 0.49666149],
       [ 0.96319517],
       [-1.60274005],
       [ 0.03012781],
       [ 0.08844452],
       [-0.08650561],
       [ 0.67161162],
       [ 0.96319517],
       [ 0.96319517],
       [ 0.96319517],
       [-0.6696727 ],
       [-0.26145573],
       [-0.26145573],
       [ 0.49666149],
       [ 0.61329491],
       [ 0.5549782 ],
       [ 0.49666149],
       [-0.20313902],
       [-1.77769018],
       [-0.55303928],
       [ 0.5549782 ],
       [ 1.37141214],
       [ 1.02151188],
       [ 1.37141214],
       [ 0.96319517],
       [        nan],
       [ 1.25477872],
       [ 0.5549782 ],
       [ 0.49666149],
       [ 1.07982859],
       [ 0.78824504],
       [ 1.42972884],
       [ 1.19646201],
       [ 1.02151188],
       [ 1.7796291 ],
       [-0.31977244],
       [-0.37808915],
       [-0.26145573],
       [-0.96125625],
       [ 0.14676123],
       [ 0.14676123],
       [-0.20313902],
       [-2.36085728],
       [ 1.25477872],
       [ 0.49666149],
       [ 0.08844452],
       [ 0.14676123],
       [ 0.08844452],
       [ 0.61329491],
       [ 0.67161162],
       [-0.96125625],
       [ 1.42972884],
       [ 1.42972884],
       [ 1.25477872],
       [ 0.43834478],
       [ 0.90487846],
       [ 0.90487846],
       [-2.12759044],
       [-0.31977244],
       [ 0.20507794],
       [-0.43640586],
       [ 0.90487846],
       [-0.37808915],
       [ 0.78824504],
       [-1.48610664],
       [ 0.5549782 ],
       [-0.31977244],
       [ 0.72992833],
       [        nan],
       [ 0.26339465],
       [-2.71075754],
       [-0.20313902],
       [ 0.90487846],
       [ 1.07982859],
       [ 0.26339465],
       [ 1.31309543],
       [-0.37808915],
       [-0.78630612],
       [-0.20313902],
       [ 0.43834478],
       [ 1.07982859],
       [ 0.26339465],
       [ 1.07982859],
       [ 0.38002807],
       [-0.08650561],
       [ 0.67161162],
       [ 0.26339465],
       [ 1.1381453 ],
       [ 1.25477872],
       [ 0.78824504],
       [ 0.61329491],
       [ 0.49666149],
       [ 0.78824504],
       [-0.08650561],
       [ 0.26339465],
       [-1.01957296],
       [ 1.1381453 ],
       [-2.01095702],
       [ 1.42972884],
       [ 0.20507794],
       [ 0.78824504],
       [-0.08650561],
       [ 0.20507794],
       [-0.37808915],
       [ 0.14676123],
       [ 0.67161162],
       [ 0.78824504],
       [        nan],
       [ 0.5549782 ],
       [-2.30254057],
       [-0.26145573],
       [        nan],
       [        nan],
       [ 0.20507794],
       [ 0.49666149],
       [ 1.19646201],
       [ 0.14676123],
       [-1.01957296],
       [-0.49472257],
       [ 0.78824504],
       [ 1.19646201],
       [ 1.07982859],
       [ 1.1381453 ],
       [ 0.03012781],
       [ 1.37141214],
       [-0.08650561],
       [-2.71075754],
       [-0.08650561],
       [ 1.07982859],
       [-0.26145573],
       [-0.20313902],
       [-0.31977244],
       [-0.37808915],
       [ 1.25477872],
       [-0.61135599],
       [ 1.02151188],
       [ 0.90487846],
       [ 1.19646201],
       [-0.61135599],
       [ 0.49666149],
       [ 0.32171136],
       [ 0.08844452],
       [ 0.49666149],
       [ 1.02151188],
       [ 0.78824504],
       [-2.53580741],
       [ 1.42972884],
       [-0.72798941],
       [ 0.20507794],
       [ 0.26339465],
       [-0.08650561],
       [ 0.84656175],
       [ 0.61329491],
       [ 1.1381453 ],
       [ 0.43834478],
       [ 1.72131239],
       [ 0.61329491],
       [ 0.43834478],
       [-0.31977244],
       [-2.18590715],
       [ 0.49666149],
       [-1.42778993],
       [-1.01957296],
       [ 0.78824504],
       [        nan],
       [ 0.84656175],
       [ 1.83794581],
       [ 0.61329491],
       [-2.01095702],
       [ 0.14676123],
       [ 0.49666149],
       [-1.77769018],
       [ 0.78824504],
       [-0.55303928],
       [ 1.19646201],
       [ 1.25477872],
       [-0.37808915],
       [ 0.5549782 ],
       [-1.2528398 ],
       [ 0.14676123],
       [-2.76907425],
       [-2.53580741],
       [-2.82739096],
       [-2.53580741],
       [ 0.72992833],
       [-2.65244083],
       [        nan],
       [-0.31977244],
       [-1.13620638],
       [ 1.66299568],
       [ 1.07982859],
       [-0.14482231],
       [ 0.32171136],
       [ 0.43834478],
       [ 0.78824504],
       [ 2.24616278],
       [ 0.72992833],
       [ 1.54636226],
       [        nan],
       [ 0.78824504],
       [ 0.5549782 ],
       [ 0.49666149],
       [-0.08650561],
       [ 0.90487846],
       [-1.8943236 ],
       [ 0.43834478],
       [ 0.14676123],
       [-0.6696727 ],
       [ 0.20507794],
       [ 0.96319517],
       [-2.88570767],
       [ 0.72992833],
       [ 0.67161162],
       [-1.07788967],
       [ 0.96319517],
       [-0.90293954],
       [ 0.84656175],
       [ 1.31309543],
       [ 1.1381453 ],
       [-1.01957296],
       [ 0.49666149],
       [ 0.72992833],
       [ 0.32171136],
       [ 0.49666149],
       [ 0.43834478],
       [ 0.78824504],
       [ 0.49666149],
       [-0.08650561],
       [-0.0281889 ],
       [-0.84462283],
       [-0.37808915],
       [ 0.78824504],
       [ 1.66299568],
       [ 1.19646201],
       [-1.01957296],
       [ 0.78824504],
       [ 0.32171136],
       [ 1.02151188],
       [ 0.61329491],
       [ 0.72992833],
       [-0.20313902],
       [-0.20313902],
       [ 0.14676123],
       [ 0.43834478],
       [ 0.26339465],
       [-0.6696727 ],
       [-1.66105676],
       [-0.37808915],
       [ 0.32171136],
       [-0.0281889 ],
       [-1.01957296],
       [ 0.49666149],
       [-0.78630612],
       [-0.55303928],
       [-0.96125625],
       [-1.2528398 ],
       [-0.14482231],
       [ 0.20507794],
       [-0.37808915],
       [-0.55303928],
       [-0.08650561],
       [ 0.20507794],
       [-0.20313902],
       [        nan],
       [-1.54442335],
       [-1.66105676],
       [-1.2528398 ],
       [ 0.26339465],
       [-0.26145573],
       [-1.8943236 ],
       [ 0.03012781],
       [-1.83600689],
       [-0.31977244],
       [-0.20313902],
       [-1.60274005],
       [-0.26145573],
       [ 0.20507794],
       [-1.83600689],
       [ 0.49666149],
       [-1.07788967],
       [ 0.84656175],
       [ 1.1381453 ],
       [-0.72798941],
       [ 0.26339465],
       [-0.55303928],
       [ 0.14676123],
       [-0.26145573],
       [-1.2528398 ],
       [-0.08650561],
       [ 1.37141214],
       [-0.43640586],
       [-0.61135599],
       [ 0.08844452],
       [-1.01957296],
       [ 1.25477872],
       [-0.37808915],
       [-0.43640586],
       [-1.31115651],
       [ 0.20507794],
       [-1.07788967],
       [-0.61135599],
       [ 0.03012781],
       [-0.26145573],
       [-0.49472257],
       [-0.0281889 ],
       [-0.31977244],
       [ 0.26339465],
       [ 1.66299568],
       [ 0.20507794],
       [-0.72798941],
       [-0.43640586],
       [-0.96125625],
       [ 0.38002807],
       [ 0.5549782 ],
       [-1.2528398 ],
       [ 0.32171136],
       [ 0.78824504],
       [ 1.07982859],
       [-0.49472257],
       [-0.6696727 ],
       [ 0.38002807],
       [-0.26145573],
       [-1.2528398 ],
       [-1.36947322],
       [-1.07788967],
       [-0.49472257],
       [ 0.43834478],
       [-1.01957296],
       [-1.66105676],
       [-1.60274005],
       [ 0.49666149],
       [-1.54442335],
       [-0.43640586],
       [ 0.61329491],
       [-1.54442335],
       [-1.13620638],
       [ 0.67161162],
       [-0.43640586],
       [-0.84462283],
       [ 0.72992833],
       [-1.71937347],
       [-1.07788967],
       [-0.49472257],
       [-0.78630612],
       [-0.96125625],
       [ 0.78824504],
       [-1.31115651],
       [-0.84462283],
       [-0.72798941],
       [-1.13620638],
       [-1.66105676],
       [-1.01957296],
       [ 0.84656175],
       [-0.26145573],
       [ 1.31309543],
       [-0.96125625],
       [-1.31115651],
       [-1.07788967],
       [ 0.90487846],
       [ 1.25477872],
       [-1.60274005],
       [ 0.49666149],
       [ 0.96319517],
       [-1.2528398 ],
       [ 1.37141214],
       [ 1.02151188],
       [-1.36947322],
       [ 1.19646201],
       [ 0.5549782 ],
       [ 1.60467897],
       [ 1.07982859],
       [ 0.38002807],
       [ 0.72992833],
       [ 1.1381453 ],
       [ 0.61329491],
       [ 0.43834478],
       [ 1.1381453 ],
       [-0.20313902],
       [ 1.66299568],
       [ 0.32171136],
       [ 0.67161162],
       [-0.31977244],
       [-2.12759044],
       [-0.0281889 ],
       [-0.61135599],
       [ 0.03012781],
       [-0.90293954],
       [ 0.32171136],
       [-0.49472257],
       [-0.08650561],
       [ 0.20507794],
       [-0.55303928],
       [-2.30254057],
       [-2.01095702],
       [ 0.38002807]])

In [21]:
# Step 2: Apply KNN Imputer
from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=3)
data_imputed = imputer.fit_transform(data_scaled)

In [22]:
data_imputed

array([[-2.03139024e-01],
       [-2.59412412e+00],
       [ 6.13294910e-01],
       [-2.03139024e-01],
       [-2.81888954e-02],
       [ 4.96661491e-01],
       [ 9.63195168e-01],
       [-1.60274005e+00],
       [ 3.01278142e-02],
       [ 8.84445238e-02],
       [-8.65056050e-02],
       [ 6.71611620e-01],
       [ 9.63195168e-01],
       [ 9.63195168e-01],
       [ 9.63195168e-01],
       [-6.69672701e-01],
       [-2.61455734e-01],
       [-2.61455734e-01],
       [ 4.96661491e-01],
       [ 6.13294910e-01],
       [ 5.54978201e-01],
       [ 4.96661491e-01],
       [-2.03139024e-01],
       [-1.77769018e+00],
       [-5.53039282e-01],
       [ 5.54978201e-01],
       [ 1.37141214e+00],
       [ 1.02151188e+00],
       [ 1.37141214e+00],
       [ 9.63195168e-01],
       [ 9.99484667e-17],
       [ 1.25477872e+00],
       [ 5.54978201e-01],
       [ 4.96661491e-01],
       [ 1.07982859e+00],
       [ 7.88245039e-01],
       [ 1.42972884e+00],
       [ 1.19646201e+00],
       [ 1.02151188e+00],
       [ 1.77962910e+00],
       [-3.19772443e-01],
       [-3.78089153e-01],
       [-2.61455734e-01],
       [-9.61256249e-01],
       [ 1.46761233e-01],
       [ 1.46761233e-01],
       [-2.03139024e-01],
       [-2.36085728e+00],
       [ 1.25477872e+00],
       [ 4.96661491e-01],
       [ 8.84445238e-02],
       [ 1.46761233e-01],
       [ 8.84445238e-02],
       [ 6.13294910e-01],
       [ 6.71611620e-01],
       [-9.61256249e-01],
       [ 1.42972884e+00],
       [ 1.42972884e+00],
       [ 1.25477872e+00],
       [ 4.38344781e-01],
       [ 9.04878458e-01],
       [ 9.04878458e-01],
       [-2.12759044e+00],
       [-3.19772443e-01],
       [ 2.05077943e-01],
       [-4.36405863e-01],
       [ 9.04878458e-01],
       [-3.78089153e-01],
       [ 7.88245039e-01],
       [-1.48610664e+00],
       [ 5.54978201e-01],
       [-3.19772443e-01],
       [ 7.29928329e-01],
       [ 9.99484667e-17],
       [ 2.63394653e-01],
       [-2.71075754e+00],
       [-2.03139024e-01],
       [ 9.04878458e-01],
       [ 1.07982859e+00],
       [ 2.63394653e-01],
       [ 1.31309543e+00],
       [-3.78089153e-01],
       [-7.86306120e-01],
       [-2.03139024e-01],
       [ 4.38344781e-01],
       [ 1.07982859e+00],
       [ 2.63394653e-01],
       [ 1.07982859e+00],
       [ 3.80028072e-01],
       [-8.65056050e-02],
       [ 6.71611620e-01],
       [ 2.63394653e-01],
       [ 1.13814530e+00],
       [ 1.25477872e+00],
       [ 7.88245039e-01],
       [ 6.13294910e-01],
       [ 4.96661491e-01],
       [ 7.88245039e-01],
       [-8.65056050e-02],
       [ 2.63394653e-01],
       [-1.01957296e+00],
       [ 1.13814530e+00],
       [-2.01095702e+00],
       [ 1.42972884e+00],
       [ 2.05077943e-01],
       [ 7.88245039e-01],
       [-8.65056050e-02],
       [ 2.05077943e-01],
       [-3.78089153e-01],
       [ 1.46761233e-01],
       [ 6.71611620e-01],
       [ 7.88245039e-01],
       [ 9.99484667e-17],
       [ 5.54978201e-01],
       [-2.30254057e+00],
       [-2.61455734e-01],
       [ 9.99484667e-17],
       [ 9.99484667e-17],
       [ 2.05077943e-01],
       [ 4.96661491e-01],
       [ 1.19646201e+00],
       [ 1.46761233e-01],
       [-1.01957296e+00],
       [-4.94722572e-01],
       [ 7.88245039e-01],
       [ 1.19646201e+00],
       [ 1.07982859e+00],
       [ 1.13814530e+00],
       [ 3.01278142e-02],
       [ 1.37141214e+00],
       [-8.65056050e-02],
       [-2.71075754e+00],
       [-8.65056050e-02],
       [ 1.07982859e+00],
       [-2.61455734e-01],
       [-2.03139024e-01],
       [-3.19772443e-01],
       [-3.78089153e-01],
       [ 1.25477872e+00],
       [-6.11355991e-01],
       [ 1.02151188e+00],
       [ 9.04878458e-01],
       [ 1.19646201e+00],
       [-6.11355991e-01],
       [ 4.96661491e-01],
       [ 3.21711362e-01],
       [ 8.84445238e-02],
       [ 4.96661491e-01],
       [ 1.02151188e+00],
       [ 7.88245039e-01],
       [-2.53580741e+00],
       [ 1.42972884e+00],
       [-7.27989411e-01],
       [ 2.05077943e-01],
       [ 2.63394653e-01],
       [-8.65056050e-02],
       [ 8.46561749e-01],
       [ 6.13294910e-01],
       [ 1.13814530e+00],
       [ 4.38344781e-01],
       [ 1.72131239e+00],
       [ 6.13294910e-01],
       [ 4.38344781e-01],
       [-3.19772443e-01],
       [-2.18590715e+00],
       [ 4.96661491e-01],
       [-1.42778993e+00],
       [-1.01957296e+00],
       [ 7.88245039e-01],
       [ 9.99484667e-17],
       [ 8.46561749e-01],
       [ 1.83794581e+00],
       [ 6.13294910e-01],
       [-2.01095702e+00],
       [ 1.46761233e-01],
       [ 4.96661491e-01],
       [-1.77769018e+00],
       [ 7.88245039e-01],
       [-5.53039282e-01],
       [ 1.19646201e+00],
       [ 1.25477872e+00],
       [-3.78089153e-01],
       [ 5.54978201e-01],
       [-1.25283980e+00],
       [ 1.46761233e-01],
       [-2.76907425e+00],
       [-2.53580741e+00],
       [-2.82739096e+00],
       [-2.53580741e+00],
       [ 7.29928329e-01],
       [-2.65244083e+00],
       [ 9.99484667e-17],
       [-3.19772443e-01],
       [-1.13620638e+00],
       [ 1.66299568e+00],
       [ 1.07982859e+00],
       [-1.44822315e-01],
       [ 3.21711362e-01],
       [ 4.38344781e-01],
       [ 7.88245039e-01],
       [ 2.24616278e+00],
       [ 7.29928329e-01],
       [ 1.54636226e+00],
       [ 9.99484667e-17],
       [ 7.88245039e-01],
       [ 5.54978201e-01],
       [ 4.96661491e-01],
       [-8.65056050e-02],
       [ 9.04878458e-01],
       [-1.89432360e+00],
       [ 4.38344781e-01],
       [ 1.46761233e-01],
       [-6.69672701e-01],
       [ 2.05077943e-01],
       [ 9.63195168e-01],
       [-2.88570767e+00],
       [ 7.29928329e-01],
       [ 6.71611620e-01],
       [-1.07788967e+00],
       [ 9.63195168e-01],
       [-9.02939539e-01],
       [ 8.46561749e-01],
       [ 1.31309543e+00],
       [ 1.13814530e+00],
       [-1.01957296e+00],
       [ 4.96661491e-01],
       [ 7.29928329e-01],
       [ 3.21711362e-01],
       [ 4.96661491e-01],
       [ 4.38344781e-01],
       [ 7.88245039e-01],
       [ 4.96661491e-01],
       [-8.65056050e-02],
       [-2.81888954e-02],
       [-8.44622830e-01],
       [-3.78089153e-01],
       [ 7.88245039e-01],
       [ 1.66299568e+00],
       [ 1.19646201e+00],
       [-1.01957296e+00],
       [ 7.88245039e-01],
       [ 3.21711362e-01],
       [ 1.02151188e+00],
       [ 6.13294910e-01],
       [ 7.29928329e-01],
       [-2.03139024e-01],
       [-2.03139024e-01],
       [ 1.46761233e-01],
       [ 4.38344781e-01],
       [ 2.63394653e-01],
       [-6.69672701e-01],
       [-1.66105676e+00],
       [-3.78089153e-01],
       [ 3.21711362e-01],
       [-2.81888954e-02],
       [-1.01957296e+00],
       [ 4.96661491e-01],
       [-7.86306120e-01],
       [-5.53039282e-01],
       [-9.61256249e-01],
       [-1.25283980e+00],
       [-1.44822315e-01],
       [ 2.05077943e-01],
       [-3.78089153e-01],
       [-5.53039282e-01],
       [-8.65056050e-02],
       [ 2.05077943e-01],
       [-2.03139024e-01],
       [ 9.99484667e-17],
       [-1.54442335e+00],
       [-1.66105676e+00],
       [-1.25283980e+00],
       [ 2.63394653e-01],
       [-2.61455734e-01],
       [-1.89432360e+00],
       [ 3.01278142e-02],
       [-1.83600689e+00],
       [-3.19772443e-01],
       [-2.03139024e-01],
       [-1.60274005e+00],
       [-2.61455734e-01],
       [ 2.05077943e-01],
       [-1.83600689e+00],
       [ 4.96661491e-01],
       [-1.07788967e+00],
       [ 8.46561749e-01],
       [ 1.13814530e+00],
       [-7.27989411e-01],
       [ 2.63394653e-01],
       [-5.53039282e-01],
       [ 1.46761233e-01],
       [-2.61455734e-01],
       [-1.25283980e+00],
       [-8.65056050e-02],
       [ 1.37141214e+00],
       [-4.36405863e-01],
       [-6.11355991e-01],
       [ 8.84445238e-02],
       [-1.01957296e+00],
       [ 1.25477872e+00],
       [-3.78089153e-01],
       [-4.36405863e-01],
       [-1.31115651e+00],
       [ 2.05077943e-01],
       [-1.07788967e+00],
       [-6.11355991e-01],
       [ 3.01278142e-02],
       [-2.61455734e-01],
       [-4.94722572e-01],
       [-2.81888954e-02],
       [-3.19772443e-01],
       [ 2.63394653e-01],
       [ 1.66299568e+00],
       [ 2.05077943e-01],
       [-7.27989411e-01],
       [-4.36405863e-01],
       [-9.61256249e-01],
       [ 3.80028072e-01],
       [ 5.54978201e-01],
       [-1.25283980e+00],
       [ 3.21711362e-01],
       [ 7.88245039e-01],
       [ 1.07982859e+00],
       [-4.94722572e-01],
       [-6.69672701e-01],
       [ 3.80028072e-01],
       [-2.61455734e-01],
       [-1.25283980e+00],
       [-1.36947322e+00],
       [-1.07788967e+00],
       [-4.94722572e-01],
       [ 4.38344781e-01],
       [-1.01957296e+00],
       [-1.66105676e+00],
       [-1.60274005e+00],
       [ 4.96661491e-01],
       [-1.54442335e+00],
       [-4.36405863e-01],
       [ 6.13294910e-01],
       [-1.54442335e+00],
       [-1.13620638e+00],
       [ 6.71611620e-01],
       [-4.36405863e-01],
       [-8.44622830e-01],
       [ 7.29928329e-01],
       [-1.71937347e+00],
       [-1.07788967e+00],
       [-4.94722572e-01],
       [-7.86306120e-01],
       [-9.61256249e-01],
       [ 7.88245039e-01],
       [-1.31115651e+00],
       [-8.44622830e-01],
       [-7.27989411e-01],
       [-1.13620638e+00],
       [-1.66105676e+00],
       [-1.01957296e+00],
       [ 8.46561749e-01],
       [-2.61455734e-01],
       [ 1.31309543e+00],
       [-9.61256249e-01],
       [-1.31115651e+00],
       [-1.07788967e+00],
       [ 9.04878458e-01],
       [ 1.25477872e+00],
       [-1.60274005e+00],
       [ 4.96661491e-01],
       [ 9.63195168e-01],
       [-1.25283980e+00],
       [ 1.37141214e+00],
       [ 1.02151188e+00],
       [-1.36947322e+00],
       [ 1.19646201e+00],
       [ 5.54978201e-01],
       [ 1.60467897e+00],
       [ 1.07982859e+00],
       [ 3.80028072e-01],
       [ 7.29928329e-01],
       [ 1.13814530e+00],
       [ 6.13294910e-01],
       [ 4.38344781e-01],
       [ 1.13814530e+00],
       [-2.03139024e-01],
       [ 1.66299568e+00],
       [ 3.21711362e-01],
       [ 6.71611620e-01],
       [-3.19772443e-01],
       [-2.12759044e+00],
       [-2.81888954e-02],
       [-6.11355991e-01],
       [ 3.01278142e-02],
       [-9.02939539e-01],
       [ 3.21711362e-01],
       [-4.94722572e-01],
       [-8.65056050e-02],
       [ 2.05077943e-01],
       [-5.53039282e-01],
       [-2.30254057e+00],
       [-2.01095702e+00],
       [ 3.80028072e-01]])

In [23]:
# Step 3: Inverse scaling back to original scale
data_imputed = scaler.inverse_transform(data_imputed)

In [24]:
data_imputed

array([[48.        ],
       [ 7.        ],
       [62.        ],
       [48.        ],
       [51.        ],
       [60.        ],
       [68.        ],
       [24.        ],
       [52.        ],
       [53.        ],
       [50.        ],
       [63.        ],
       [68.        ],
       [68.        ],
       [68.        ],
       [40.        ],
       [47.        ],
       [47.        ],
       [60.        ],
       [62.        ],
       [61.        ],
       [60.        ],
       [48.        ],
       [21.        ],
       [42.        ],
       [61.        ],
       [75.        ],
       [69.        ],
       [75.        ],
       [68.        ],
       [51.48337596],
       [73.        ],
       [61.        ],
       [60.        ],
       [70.        ],
       [65.        ],
       [76.        ],
       [72.        ],
       [69.        ],
       [82.        ],
       [46.        ],
       [45.        ],
       [47.        ],
       [35.        ],
       [54.        ],
       [54.        ],
       [48.        ],
       [11.        ],
       [73.        ],
       [60.        ],
       [53.        ],
       [54.        ],
       [53.        ],
       [62.        ],
       [63.        ],
       [35.        ],
       [76.        ],
       [76.        ],
       [73.        ],
       [59.        ],
       [67.        ],
       [67.        ],
       [15.        ],
       [46.        ],
       [55.        ],
       [44.        ],
       [67.        ],
       [45.        ],
       [65.        ],
       [26.        ],
       [61.        ],
       [46.        ],
       [64.        ],
       [51.48337596],
       [56.        ],
       [ 5.        ],
       [48.        ],
       [67.        ],
       [70.        ],
       [56.        ],
       [74.        ],
       [45.        ],
       [38.        ],
       [48.        ],
       [59.        ],
       [70.        ],
       [56.        ],
       [70.        ],
       [58.        ],
       [50.        ],
       [63.        ],
       [56.        ],
       [71.        ],
       [73.        ],
       [65.        ],
       [62.        ],
       [60.        ],
       [65.        ],
       [50.        ],
       [56.        ],
       [34.        ],
       [71.        ],
       [17.        ],
       [76.        ],
       [55.        ],
       [65.        ],
       [50.        ],
       [55.        ],
       [45.        ],
       [54.        ],
       [63.        ],
       [65.        ],
       [51.48337596],
       [61.        ],
       [12.        ],
       [47.        ],
       [51.48337596],
       [51.48337596],
       [55.        ],
       [60.        ],
       [72.        ],
       [54.        ],
       [34.        ],
       [43.        ],
       [65.        ],
       [72.        ],
       [70.        ],
       [71.        ],
       [52.        ],
       [75.        ],
       [50.        ],
       [ 5.        ],
       [50.        ],
       [70.        ],
       [47.        ],
       [48.        ],
       [46.        ],
       [45.        ],
       [73.        ],
       [41.        ],
       [69.        ],
       [67.        ],
       [72.        ],
       [41.        ],
       [60.        ],
       [57.        ],
       [53.        ],
       [60.        ],
       [69.        ],
       [65.        ],
       [ 8.        ],
       [76.        ],
       [39.        ],
       [55.        ],
       [56.        ],
       [50.        ],
       [66.        ],
       [62.        ],
       [71.        ],
       [59.        ],
       [81.        ],
       [62.        ],
       [59.        ],
       [46.        ],
       [14.        ],
       [60.        ],
       [27.        ],
       [34.        ],
       [65.        ],
       [51.48337596],
       [66.        ],
       [83.        ],
       [62.        ],
       [17.        ],
       [54.        ],
       [60.        ],
       [21.        ],
       [65.        ],
       [42.        ],
       [72.        ],
       [73.        ],
       [45.        ],
       [61.        ],
       [30.        ],
       [54.        ],
       [ 4.        ],
       [ 8.        ],
       [ 3.        ],
       [ 8.        ],
       [64.        ],
       [ 6.        ],
       [51.48337596],
       [46.        ],
       [32.        ],
       [80.        ],
       [70.        ],
       [49.        ],
       [57.        ],
       [59.        ],
       [65.        ],
       [90.        ],
       [64.        ],
       [78.        ],
       [51.48337596],
       [65.        ],
       [61.        ],
       [60.        ],
       [50.        ],
       [67.        ],
       [19.        ],
       [59.        ],
       [54.        ],
       [40.        ],
       [55.        ],
       [68.        ],
       [ 2.        ],
       [64.        ],
       [63.        ],
       [33.        ],
       [68.        ],
       [36.        ],
       [66.        ],
       [74.        ],
       [71.        ],
       [34.        ],
       [60.        ],
       [64.        ],
       [57.        ],
       [60.        ],
       [59.        ],
       [65.        ],
       [60.        ],
       [50.        ],
       [51.        ],
       [37.        ],
       [45.        ],
       [65.        ],
       [80.        ],
       [72.        ],
       [34.        ],
       [65.        ],
       [57.        ],
       [69.        ],
       [62.        ],
       [64.        ],
       [48.        ],
       [48.        ],
       [54.        ],
       [59.        ],
       [56.        ],
       [40.        ],
       [23.        ],
       [45.        ],
       [57.        ],
       [51.        ],
       [34.        ],
       [60.        ],
       [38.        ],
       [42.        ],
       [35.        ],
       [30.        ],
       [49.        ],
       [55.        ],
       [45.        ],
       [42.        ],
       [50.        ],
       [55.        ],
       [48.        ],
       [51.48337596],
       [25.        ],
       [23.        ],
       [30.        ],
       [56.        ],
       [47.        ],
       [19.        ],
       [52.        ],
       [20.        ],
       [46.        ],
       [48.        ],
       [24.        ],
       [47.        ],
       [55.        ],
       [20.        ],
       [60.        ],
       [33.        ],
       [66.        ],
       [71.        ],
       [39.        ],
       [56.        ],
       [42.        ],
       [54.        ],
       [47.        ],
       [30.        ],
       [50.        ],
       [75.        ],
       [44.        ],
       [41.        ],
       [53.        ],
       [34.        ],
       [73.        ],
       [45.        ],
       [44.        ],
       [29.        ],
       [55.        ],
       [33.        ],
       [41.        ],
       [52.        ],
       [47.        ],
       [43.        ],
       [51.        ],
       [46.        ],
       [56.        ],
       [80.        ],
       [55.        ],
       [39.        ],
       [44.        ],
       [35.        ],
       [58.        ],
       [61.        ],
       [30.        ],
       [57.        ],
       [65.        ],
       [70.        ],
       [43.        ],
       [40.        ],
       [58.        ],
       [47.        ],
       [30.        ],
       [28.        ],
       [33.        ],
       [43.        ],
       [59.        ],
       [34.        ],
       [23.        ],
       [24.        ],
       [60.        ],
       [25.        ],
       [44.        ],
       [62.        ],
       [25.        ],
       [32.        ],
       [63.        ],
       [44.        ],
       [37.        ],
       [64.        ],
       [22.        ],
       [33.        ],
       [43.        ],
       [38.        ],
       [35.        ],
       [65.        ],
       [29.        ],
       [37.        ],
       [39.        ],
       [32.        ],
       [23.        ],
       [34.        ],
       [66.        ],
       [47.        ],
       [74.        ],
       [35.        ],
       [29.        ],
       [33.        ],
       [67.        ],
       [73.        ],
       [24.        ],
       [60.        ],
       [68.        ],
       [30.        ],
       [75.        ],
       [69.        ],
       [28.        ],
       [72.        ],
       [61.        ],
       [79.        ],
       [70.        ],
       [58.        ],
       [64.        ],
       [71.        ],
       [62.        ],
       [59.        ],
       [71.        ],
       [48.        ],
       [80.        ],
       [57.        ],
       [63.        ],
       [46.        ],
       [15.        ],
       [51.        ],
       [41.        ],
       [52.        ],
       [36.        ],
       [57.        ],
       [43.        ],
       [50.        ],
       [55.        ],
       [42.        ],
       [12.        ],
       [17.        ],
       [58.        ]])

In [25]:
# Step 4: Convert back to DataFrame
imputed_df = pd.DataFrame(data_imputed, columns=["age"])

In [26]:
imputed_df

      age
0    48.0
1     7.0
2    62.0
3    48.0
4    51.0
..    ...
395  55.0
396  42.0
397  12.0
398  17.0
399  58.0

[400 rows x 1 columns]

In [27]:
dataset[["age"]] =np.round(imputed_df).astype(int)

In [28]:
dataset

,id,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,bu,sc,sod,pot,hemo,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,0,48,80.0,1.020,1,0.0,NaN,normal,notpresent,notpresent,121.0,36.0,1.2,NaN,NaN,15.4,44,7800,5.2,yes,yes,no,good,no,no,ckd
1,1,7,50.0,1.020,4,0.0,NaN,normal,notpresent,notpresent,NaN,18.0,0.8,NaN,NaN,11.3,38,6000,NaN,no,no,no,good,no,no,ckd
2,2,62,80.0,1.010,2,3.0,normal,normal,notpresent,notpresent,423.0,53.0,1.8,NaN,NaN,9.6,31,7500,NaN,no,yes,no,poor,no,yes,ckd
3,3,48,70.0,1.005,4,0.0,normal,abnormal,present,notpresent,117.0,56.0,3.8,111.0,2.5,11.2,32,6700,3.9,yes,no,no,poor,yes,yes,ckd
4,4,51,80.0,1.010,2,0.0,normal,normal,notpresent,notpresent,106.0,26.0,1.4,NaN,NaN,11.6,35,7300,4.6,no,no,no,good,no,no,ckd
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,395,55,80.0,1.020,0,0.0,normal,normal,notpresent,notpresent,140.0,49.0,0.5,150.0,4.9,15.7,47,6700,4.9,no,no,no,good,no,no,notckd
396,396,42,70.0,1.025,0,0.0,normal,normal,notpresent,notpresent,75.0,31.0,1.2,141.0,3.5,16.5,54,7800,6.2,no,no,no,good,no,no,notckd
397,397,12,80.0,1.020,0,0.0,normal,normal,notpresent,notpresent,100.0,26.0,0.6,137.0,4.4,15.8,49,6600,5.4,no,no,no,good,no,no,notckd
398,398,17,60.0,1.025,0,0.0,normal,normal,notpresent,notpresent,114.0,50.0,1.0,135.0,4.9,14.2,51,7200,5.9,no,no,no,good,no,no,notckd
399,399,58,80.0,1.025,0,0.0,normal,normal,notpresent,notpresent,131.0,18.0,1.1,141.0,3.5,15.8,53,6800,6.1,no,no,no,good,no,no,notckd

In [29]:
from sklearn.preprocessing import StandardScaler
# Scale features before imputation
scaler = StandardScaler()
data_scaled = scaler.fit_transform(dataset[["bp"]])

In [30]:
# Step 2: Apply KNN Imputer
from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=3)
data_imputed = imputer.fit_transform(data_scaled)

In [31]:
# Step 3: Inverse scaling back to original scale
data_imputed = scaler.inverse_transform(data_imputed)

In [32]:
# Step 4: Convert back to DataFrame
imputed_df = pd.DataFrame(data_imputed, columns=["bp"])

In [33]:
imputed_df

       bp
0    80.0
1    50.0
2    80.0
3    70.0
4    80.0
..    ...
395  80.0
396  70.0
397  80.0
398  60.0
399  80.0

[400 rows x 1 columns]

In [34]:
dataset[["bp"]] =np.round(imputed_df).astype(int)

In [35]:
dataset

,id,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,bu,sc,sod,pot,hemo,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,0,48,80,1.020,1,0.0,NaN,normal,notpresent,notpresent,121.0,36.0,1.2,NaN,NaN,15.4,44,7800,5.2,yes,yes,no,good,no,no,ckd
1,1,7,50,1.020,4,0.0,NaN,normal,notpresent,notpresent,NaN,18.0,0.8,NaN,NaN,11.3,38,6000,NaN,no,no,no,good,no,no,ckd
2,2,62,80,1.010,2,3.0,normal,normal,notpresent,notpresent,423.0,53.0,1.8,NaN,NaN,9.6,31,7500,NaN,no,yes,no,poor,no,yes,ckd
3,3,48,70,1.005,4,0.0,normal,abnormal,present,notpresent,117.0,56.0,3.8,111.0,2.5,11.2,32,6700,3.9,yes,no,no,poor,yes,yes,ckd
4,4,51,80,1.010,2,0.0,normal,normal,notpresent,notpresent,106.0,26.0,1.4,NaN,NaN,11.6,35,7300,4.6,no,no,no,good,no,no,ckd
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,395,55,80,1.020,0,0.0,normal,normal,notpresent,notpresent,140.0,49.0,0.5,150.0,4.9,15.7,47,6700,4.9,no,no,no,good,no,no,notckd
396,396,42,70,1.025,0,0.0,normal,normal,notpresent,notpresent,75.0,31.0,1.2,141.0,3.5,16.5,54,7800,6.2,no,no,no,good,no,no,notckd
397,397,12,80,1.020,0,0.0,normal,normal,notpresent,notpresent,100.0,26.0,0.6,137.0,4.4,15.8,49,6600,5.4,no,no,no,good,no,no,notckd
398,398,17,60,1.025,0,0.0,normal,normal,notpresent,notpresent,114.0,50.0,1.0,135.0,4.9,14.2,51,7200,5.9,no,no,no,good,no,no,notckd
399,399,58,80,1.025,0,0.0,normal,normal,notpresent,notpresent,131.0,18.0,1.1,141.0,3.5,15.8,53,6800,6.1,no,no,no,good,no,no,notckd

In [36]:
from sklearn.preprocessing import StandardScaler
# Scale features before imputation
scaler = StandardScaler()
data_scaled = scaler.fit_transform(dataset[["sg"]])

In [37]:
# Step 2: Apply KNN Imputer
from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=3)
data_imputed = imputer.fit_transform(data_scaled)

# Step 3: Inverse scaling back to original scale
data_imputed = scaler.inverse_transform(data_imputed)

# Step 4: Convert back to DataFrame
imputed_df = pd.DataFrame(data_imputed, columns=["sg"])

dataset[["sg"]] =np.round(imputed_df).astype(int)

In [38]:
data_imputed

array([[1.02      ],
       [1.02      ],
       [1.01      ],
       [1.005     ],
       [1.01      ],
       [1.015     ],
       [1.01      ],
       [1.015     ],
       [1.015     ],
       [1.02      ],
       [1.01      ],
       [1.01      ],
       [1.015     ],
       [1.01740793],
       [1.01      ],
       [1.015     ],
       [1.015     ],
       [1.01740793],
       [1.025     ],
       [1.015     ],
       [1.015     ],
       [1.01740793],
       [1.025     ],
       [1.01      ],
       [1.015     ],
       [1.025     ],
       [1.015     ],
       [1.01      ],
       [1.01740793],
       [1.005     ],
       [1.01740793],
       [1.015     ],
       [1.01      ],
       [1.02      ],
       [1.01      ],
       [1.02      ],
       [1.015     ],
       [1.01740793],
       [1.02      ],
       [1.01      ],
       [1.01      ],
       [1.01      ],
       [1.01      ],
       [1.01      ],
       [1.01      ],
       [1.02      ],
       [1.015     ],
       [1.01      ],
       [1.005     ],
       [1.01      ],
       [1.01740793],
       [1.015     ],
       [1.015     ],
       [1.015     ],
       [1.01      ],
       [1.005     ],
       [1.015     ],
       [1.01740793],
       [1.02      ],
       [1.01740793],
       [1.02      ],
       [1.01      ],
       [1.02      ],
       [1.015     ],
       [1.01      ],
       [1.01      ],
       [1.02      ],
       [1.02      ],
       [1.01      ],
       [1.015     ],
       [1.015     ],
       [1.01      ],
       [1.01      ],
       [1.015     ],
       [1.015     ],
       [1.015     ],
       [1.005     ],
       [1.01      ],
       [1.01740793],
       [1.01      ],
       [1.01      ],
       [1.01740793],
       [1.01740793],
       [1.015     ],
       [1.01      ],
       [1.015     ],
       [1.01740793],
       [1.005     ],
       [1.01      ],
       [1.02      ],
       [1.01      ],
       [1.015     ],
       [1.01      ],
       [1.01      ],
       [1.01      ],
       [1.015     ],
       [1.01      ],
       [1.015     ],
       [1.01740793],
       [1.01740793],
       [1.015     ],
       [1.015     ],
       [1.01      ],
       [1.015     ],
       [1.01740793],
       [1.015     ],
       [1.01740793],
       [1.015     ],
       [1.015     ],
       [1.01740793],
       [1.015     ],
       [1.01      ],
       [1.015     ],
       [1.015     ],
       [1.015     ],
       [1.01      ],
       [1.015     ],
       [1.02      ],
       [1.01      ],
       [1.01      ],
       [1.025     ],
       [1.01740793],
       [1.01740793],
       [1.015     ],
       [1.015     ],
       [1.01740793],
       [1.015     ],
       [1.015     ],
       [1.015     ],
       [1.025     ],
       [1.01      ],
       [1.01      ],
       [1.01740793],
       [1.015     ],
       [1.01      ],
       [1.015     ],
       [1.02      ],
       [1.01      ],
       [1.01      ],
       [1.015     ],
       [1.01      ],
       [1.01      ],
       [1.01740793],
       [1.015     ],
       [1.01      ],
       [1.015     ],
       [1.01      ],
       [1.01      ],
       [1.01740793],
       [1.02      ],
       [1.025     ],
       [1.01740793],
       [1.01      ],
       [1.01      ],
       [1.005     ],
       [1.02      ],
       [1.015     ],
       [1.025     ],
       [1.02      ],
       [1.01      ],
       [1.01740793],
       [1.015     ],
       [1.01740793],
       [1.01      ],
       [1.015     ],
       [1.02      ],
       [1.01740793],
       [1.02      ],
       [1.015     ],
       [1.01      ],
       [1.015     ],
       [1.02      ],
       [1.01      ],
       [1.015     ],
       [1.01740793],
       [1.01      ],
       [1.01      ],
       [1.015     ],
       [1.02      ],
       [1.01      ],
       [1.01      ],
       [1.025     ],
       [1.02      ],
       [1.015     ],
       [1.015     ],
       [1.02      ],
       [1.02      ],
       [1.01      ],
       [1.01740793],
       [1.01      ],
       [1.01      ],
       [1.01      ],
       [1.015     ],
       [1.025     ],
       [1.01      ],
       [1.02      ],
       [1.01      ],
       [1.01740793],
       [1.02      ],
       [1.015     ],
       [1.025     ],
       [1.01740793],
       [1.01740793],
       [1.01740793],
       [1.01      ],
       [1.01740793],
       [1.01      ],
       [1.01      ],
       [1.01740793],
       [1.02      ],
       [1.015     ],
       [1.015     ],
       [1.015     ],
       [1.01      ],
       [1.015     ],
       [1.01      ],
       [1.01      ],
       [1.01      ],
       [1.015     ],
       [1.01      ],
       [1.01      ],
       [1.02      ],
       [1.01740793],
       [1.01      ],
       [1.02      ],
       [1.01      ],
       [1.015     ],
       [1.015     ],
       [1.01740793],
       [1.01      ],
       [1.01      ],
       [1.01740793],
       [1.015     ],
       [1.015     ],
       [1.01      ],
       [1.01      ],
       [1.01740793],
       [1.015     ],
       [1.01740793],
       [1.015     ],
       [1.015     ],
       [1.015     ],
       [1.01      ],
       [1.02      ],
       [1.015     ],
       [1.01740793],
       [1.015     ],
       [1.025     ],
       [1.01      ],
       [1.01      ],
       [1.025     ],
       [1.025     ],
       [1.025     ],
       [1.025     ],
       [1.025     ],
       [1.025     ],
       [1.025     ],
       [1.02      ],
       [1.02      ],
       [1.02      ],
       [1.02      ],
       [1.02      ],
       [1.02      ],
       [1.02      ],
       [1.02      ],
       [1.02      ],
       [1.02      ],
       [1.025     ],
       [1.01740793],
       [1.025     ],
       [1.025     ],
       [1.025     ],
       [1.025     ],
       [1.02      ],
       [1.02      ],
       [1.02      ],
       [1.025     ],
       [1.025     ],
       [1.02      ],
       [1.025     ],
       [1.01740793],
       [1.025     ],
       [1.02      ],
       [1.02      ],
       [1.025     ],
       [1.02      ],
       [1.02      ],
       [1.025     ],
       [1.025     ],
       [1.02      ],
       [1.02      ],
       [1.025     ],
       [1.02      ],
       [1.02      ],
       [1.02      ],
       [1.01740793],
       [1.02      ],
       [1.025     ],
       [1.02      ],
       [1.02      ],
       [1.02      ],
       [1.025     ],
       [1.02      ],
       [1.02      ],
       [1.025     ],
       [1.02      ],
       [1.02      ],
       [1.02      ],
       [1.025     ],
       [1.02      ],
       [1.02      ],
       [1.025     ],
       [1.02      ],
       [1.02      ],
       [1.025     ],
       [1.025     ],
       [1.02      ],
       [1.02      ],
       [1.025     ],
       [1.02      ],
       [1.02      ],
       [1.02      ],
       [1.01740793],
       [1.025     ],
       [1.02      ],
       [1.02      ],
       [1.02      ],
       [1.025     ],
       [1.02      ],
       [1.025     ],
       [1.02      ],
       [1.025     ],
       [1.025     ],
       [1.02      ],
       [1.025     ],
       [1.02      ],
       [1.02      ],
       [1.025     ],
       [1.02      ],
       [1.02      ],
       [1.025     ],
       [1.025     ],
       [1.02      ],
       [1.025     ],
       [1.02      ],
       [1.025     ],
       [1.01740793],
       [1.025     ],
       [1.02      ],
       [1.025     ],
       [1.025     ],
       [1.02      ],
       [1.02      ],
       [1.02      ],
       [1.025     ],
       [1.02      ],
       [1.025     ],
       [1.025     ],
       [1.02      ],
       [1.02      ],
       [1.025     ],
       [1.02      ],
       [1.025     ],
       [1.025     ],
       [1.025     ],
       [1.02      ],
       [1.025     ],
       [1.025     ],
       [1.025     ],
       [1.02      ],
       [1.02      ],
       [1.025     ],
       [1.02      ],
       [1.025     ],
       [1.025     ],
       [1.02      ],
       [1.025     ],
       [1.02      ],
       [1.025     ],
       [1.025     ],
       [1.02      ],
       [1.025     ],
       [1.025     ],
       [1.025     ],
       [1.02      ],
       [1.02      ],
       [1.025     ],
       [1.025     ],
       [1.02      ],
       [1.025     ],
       [1.025     ],
       [1.025     ],
       [1.02      ],
       [1.025     ],
       [1.02      ],
       [1.02      ],
       [1.025     ],
       [1.02      ],
       [1.025     ],
       [1.025     ]])

In [39]:
from sklearn.preprocessing import StandardScaler
# Scale features before imputation
scaler = StandardScaler()
data_scaled = scaler.fit_transform(dataset[["al"]])

# Step 2: Apply KNN Imputer
from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=3)
data_imputed = imputer.fit_transform(data_scaled)

# Step 3: Inverse scaling back to original scale
data_imputed = scaler.inverse_transform(data_imputed)

# Step 4: Convert back to DataFrame
imputed_df = pd.DataFrame(data_imputed, columns=["al"])

dataset[["al"]] =np.round(imputed_df).astype(int)

In [40]:
dataset[["al"]].isnull().sum()

al    0
dtype: int64

In [41]:
from sklearn.preprocessing import StandardScaler
# Scale features before imputation
scaler = StandardScaler()
data_scaled = scaler.fit_transform(dataset[["su"]])

# Step 2: Apply KNN Imputer
from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=3)
data_imputed = imputer.fit_transform(data_scaled)

# Step 3: Inverse scaling back to original scale
data_imputed = scaler.inverse_transform(data_imputed)

# Step 4: Convert back to DataFrame
imputed_df = pd.DataFrame(data_imputed, columns=["su"])

dataset[["su"]] =np.round(imputed_df).astype(int)

In [42]:
dataset[["su"]].isnull().sum()

su    0
dtype: int64

In [43]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 26 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              400 non-null    int64
 1   age             400 non-null    int64
 2   bp              400 non-null    int64
 3   sg              400 non-null    int64
 4   al              400 non-null    int64
 5   su              400 non-null    int64
 6   rbc             248 non-null    object
 7   pc              335 non-null    object
 8   pcc             396 non-null    object
 9   ba              396 non-null    object
 10  bgr             356 non-null    float64
 11  bu              381 non-null    float64
 12  sc              383 non-null    float64
 13  sod             313 non-null    float64
 14  pot             312 non-null    float64
 15  hemo            348 non-null    float64
 16  pcv             330 non-null    object
 17  wc              295 non-null    object
 18  rc              270 non-null    object
 19  htn             398 non-null    object
 20  dm              398 non-null    object
 21  cad             398 non-null    object
 22  appet           399 non-null    object
 23  pe              399 non-null    object
 24  ane             399 non-null    object
 25  classification  400 non-null    object
dtypes: float64(6), int64(6), object(14)
memory usage: 81.4+ KB

In [44]:
dataset[["rbc"]].value_counts()

rbc
normal      201
abnormal     47
Name: count, dtype: int64

In [45]:
dataset

,id,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,bu,sc,sod,pot,hemo,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,0,48,80,1,1,0,NaN,normal,notpresent,notpresent,121.0,36.0,1.2,NaN,NaN,15.4,44,7800,5.2,yes,yes,no,good,no,no,ckd
1,1,7,50,1,4,0,NaN,normal,notpresent,notpresent,NaN,18.0,0.8,NaN,NaN,11.3,38,6000,NaN,no,no,no,good,no,no,ckd
2,2,62,80,1,2,3,normal,normal,notpresent,notpresent,423.0,53.0,1.8,NaN,NaN,9.6,31,7500,NaN,no,yes,no,poor,no,yes,ckd
3,3,48,70,1,4,0,normal,abnormal,present,notpresent,117.0,56.0,3.8,111.0,2.5,11.2,32,6700,3.9,yes,no,no,poor,yes,yes,ckd
4,4,51,80,1,2,0,normal,normal,notpresent,notpresent,106.0,26.0,1.4,NaN,NaN,11.6,35,7300,4.6,no,no,no,good,no,no,ckd
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,395,55,80,1,0,0,normal,normal,notpresent,notpresent,140.0,49.0,0.5,150.0,4.9,15.7,47,6700,4.9,no,no,no,good,no,no,notckd
396,396,42,70,1,0,0,normal,normal,notpresent,notpresent,75.0,31.0,1.2,141.0,3.5,16.5,54,7800,6.2,no,no,no,good,no,no,notckd
397,397,12,80,1,0,0,normal,normal,notpresent,notpresent,100.0,26.0,0.6,137.0,4.4,15.8,49,6600,5.4,no,no,no,good,no,no,notckd
398,398,17,60,1,0,0,normal,normal,notpresent,notpresent,114.0,50.0,1.0,135.0,4.9,14.2,51,7200,5.9,no,no,no,good,no,no,notckd
399,399,58,80,1,0,0,normal,normal,notpresent,notpresent,131.0,18.0,1.1,141.0,3.5,15.8,53,6800,6.1,no,no,no,good,no,no,notckd

In [46]:
#onehotencoding
dataset = pd.get_dummies(dataset, columns=["rbc"], drop_first=True, dummy_na=False, dtype=int)

In [47]:
dataset

,id,age,bp,sg,al,su,pc,pcc,ba,bgr,bu,sc,sod,pot,hemo,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification,rbc_normal
0,0,48,80,1,1,0,normal,notpresent,notpresent,121.0,36.0,1.2,NaN,NaN,15.4,44,7800,5.2,yes,yes,no,good,no,no,ckd,0
1,1,7,50,1,4,0,normal,notpresent,notpresent,NaN,18.0,0.8,NaN,NaN,11.3,38,6000,NaN,no,no,no,good,no,no,ckd,0
2,2,62,80,1,2,3,normal,notpresent,notpresent,423.0,53.0,1.8,NaN,NaN,9.6,31,7500,NaN,no,yes,no,poor,no,yes,ckd,1
3,3,48,70,1,4,0,abnormal,present,notpresent,117.0,56.0,3.8,111.0,2.5,11.2,32,6700,3.9,yes,no,no,poor,yes,yes,ckd,1
4,4,51,80,1,2,0,normal,notpresent,notpresent,106.0,26.0,1.4,NaN,NaN,11.6,35,7300,4.6,no,no,no,good,no,no,ckd,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,395,55,80,1,0,0,normal,notpresent,notpresent,140.0,49.0,0.5,150.0,4.9,15.7,47,6700,4.9,no,no,no,good,no,no,notckd,1
396,396,42,70,1,0,0,normal,notpresent,notpresent,75.0,31.0,1.2,141.0,3.5,16.5,54,7800,6.2,no,no,no,good,no,no,notckd,1
397,397,12,80,1,0,0,normal,notpresent,notpresent,100.0,26.0,0.6,137.0,4.4,15.8,49,6600,5.4,no,no,no,good,no,no,notckd,1
398,398,17,60,1,0,0,normal,notpresent,notpresent,114.0,50.0,1.0,135.0,4.9,14.2,51,7200,5.9,no,no,no,good,no,no,notckd,1
399,399,58,80,1,0,0,normal,notpresent,notpresent,131.0,18.0,1.1,141.0,3.5,15.8,53,6800,6.1,no,no,no,good,no,no,notckd,1

In [48]:
# Scale features before imputation
scaler = StandardScaler()
data_scaled = scaler.fit_transform(dataset[["rbc_normal"]])

# Step 2: Apply KNN Imputer
from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=3)
data_imputed = imputer.fit_transform(data_scaled)

# Step 3: Inverse scaling back to original scale
data_imputed = scaler.inverse_transform(data_imputed)

# Step 4: Convert back to DataFrame
imputed_df = pd.DataFrame(data_imputed, columns=["rbc_normal"])

dataset[["rbc_normal"]] =np.round(imputed_df).astype(int)

In [49]:
dataset[["rbc_normal"]].isnull().sum()

rbc_normal    0
dtype: int64

In [50]:
dataset[["pc"]].isnull().sum()
dataset[["pc"]].value_counts()

pc
normal      259
abnormal     76
Name: count, dtype: int64

In [51]:
#onehotencoding
dataset = pd.get_dummies(dataset, columns=["pc"], drop_first=True, dummy_na=False, dtype=int)
dataset

,id,age,bp,sg,al,su,pcc,ba,bgr,bu,sc,sod,pot,hemo,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification,rbc_normal,pc_normal
0,0,48,80,1,1,0,notpresent,notpresent,121.0,36.0,1.2,NaN,NaN,15.4,44,7800,5.2,yes,yes,no,good,no,no,ckd,0,1
1,1,7,50,1,4,0,notpresent,notpresent,NaN,18.0,0.8,NaN,NaN,11.3,38,6000,NaN,no,no,no,good,no,no,ckd,0,1
2,2,62,80,1,2,3,notpresent,notpresent,423.0,53.0,1.8,NaN,NaN,9.6,31,7500,NaN,no,yes,no,poor,no,yes,ckd,1,1
3,3,48,70,1,4,0,present,notpresent,117.0,56.0,3.8,111.0,2.5,11.2,32,6700,3.9,yes,no,no,poor,yes,yes,ckd,1,0
4,4,51,80,1,2,0,notpresent,notpresent,106.0,26.0,1.4,NaN,NaN,11.6,35,7300,4.6,no,no,no,good,no,no,ckd,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,395,55,80,1,0,0,notpresent,notpresent,140.0,49.0,0.5,150.0,4.9,15.7,47,6700,4.9,no,no,no,good,no,no,notckd,1,1
396,396,42,70,1,0,0,notpresent,notpresent,75.0,31.0,1.2,141.0,3.5,16.5,54,7800,6.2,no,no,no,good,no,no,notckd,1,1
397,397,12,80,1,0,0,notpresent,notpresent,100.0,26.0,0.6,137.0,4.4,15.8,49,6600,5.4,no,no,no,good,no,no,notckd,1,1
398,398,17,60,1,0,0,notpresent,notpresent,114.0,50.0,1.0,135.0,4.9,14.2,51,7200,5.9,no,no,no,good,no,no,notckd,1,1
399,399,58,80,1,0,0,notpresent,notpresent,131.0,18.0,1.1,141.0,3.5,15.8,53,6800,6.1,no,no,no,good,no,no,notckd,1,1

In [52]:
# Scale features before imputation
scaler = StandardScaler()
data_scaled = scaler.fit_transform(dataset[["pc_normal"]])

# Step 2: Apply KNN Imputer
from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=3)
data_imputed = imputer.fit_transform(data_scaled)

# Step 3: Inverse scaling back to original scale
data_imputed = scaler.inverse_transform(data_imputed)

# Step 4: Convert back to DataFrame
imputed_df = pd.DataFrame(data_imputed, columns=["pc_normal"])

dataset[["pc_normal"]] =np.round(imputed_df).astype(int)

In [53]:
dataset[["pc_normal"]].isnull().sum()

pc_normal    0
dtype: int64

In [54]:
dataset[["pcc"]].value_counts()

pcc
notpresent    354
present        42
Name: count, dtype: int64

In [55]:
#onehotencoding
dataset = pd.get_dummies(dataset, columns=["pcc"], drop_first=True, dummy_na=False, dtype=int)
dataset

,id,age,bp,sg,al,su,ba,bgr,bu,sc,sod,pot,hemo,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification,rbc_normal,pc_normal,pcc_present
0,0,48,80,1,1,0,notpresent,121.0,36.0,1.2,NaN,NaN,15.4,44,7800,5.2,yes,yes,no,good,no,no,ckd,0,1,0
1,1,7,50,1,4,0,notpresent,NaN,18.0,0.8,NaN,NaN,11.3,38,6000,NaN,no,no,no,good,no,no,ckd,0,1,0
2,2,62,80,1,2,3,notpresent,423.0,53.0,1.8,NaN,NaN,9.6,31,7500,NaN,no,yes,no,poor,no,yes,ckd,1,1,0
3,3,48,70,1,4,0,notpresent,117.0,56.0,3.8,111.0,2.5,11.2,32,6700,3.9,yes,no,no,poor,yes,yes,ckd,1,0,1
4,4,51,80,1,2,0,notpresent,106.0,26.0,1.4,NaN,NaN,11.6,35,7300,4.6,no,no,no,good,no,no,ckd,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,395,55,80,1,0,0,notpresent,140.0,49.0,0.5,150.0,4.9,15.7,47,6700,4.9,no,no,no,good,no,no,notckd,1,1,0
396,396,42,70,1,0,0,notpresent,75.0,31.0,1.2,141.0,3.5,16.5,54,7800,6.2,no,no,no,good,no,no,notckd,1,1,0
397,397,12,80,1,0,0,notpresent,100.0,26.0,0.6,137.0,4.4,15.8,49,6600,5.4,no,no,no,good,no,no,notckd,1,1,0
398,398,17,60,1,0,0,notpresent,114.0,50.0,1.0,135.0,4.9,14.2,51,7200,5.9,no,no,no,good,no,no,notckd,1,1,0
399,399,58,80,1,0,0,notpresent,131.0,18.0,1.1,141.0,3.5,15.8,53,6800,6.1,no,no,no,good,no,no,notckd,1,1,0

In [56]:
# Scale features before imputation
scaler = StandardScaler()
data_scaled = scaler.fit_transform(dataset[["pcc_present"]])

# Step 2: Apply KNN Imputer
from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=3)
data_imputed = imputer.fit_transform(data_scaled)

# Step 3: Inverse scaling back to original scale
data_imputed = scaler.inverse_transform(data_imputed)

# Step 4: Convert back to DataFrame
imputed_df = pd.DataFrame(data_imputed, columns=["pcc_present"])

dataset[["pcc_present"]] =np.round(imputed_df).astype(int)

In [57]:
dataset[["pcc_present"]].isnull().sum()

pcc_present    0
dtype: int64

In [58]:
dataset[["ba"]].value_counts()

ba
notpresent    374
present        22
Name: count, dtype: int64

In [59]:
#onehotencoding
dataset = pd.get_dummies(dataset, columns=["ba"], drop_first=True, dummy_na=False, dtype=int)
dataset

,id,age,bp,sg,al,su,bgr,bu,sc,sod,pot,hemo,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification,rbc_normal,pc_normal,pcc_present,ba_present
0,0,48,80,1,1,0,121.0,36.0,1.2,NaN,NaN,15.4,44,7800,5.2,yes,yes,no,good,no,no,ckd,0,1,0,0
1,1,7,50,1,4,0,NaN,18.0,0.8,NaN,NaN,11.3,38,6000,NaN,no,no,no,good,no,no,ckd,0,1,0,0
2,2,62,80,1,2,3,423.0,53.0,1.8,NaN,NaN,9.6,31,7500,NaN,no,yes,no,poor,no,yes,ckd,1,1,0,0
3,3,48,70,1,4,0,117.0,56.0,3.8,111.0,2.5,11.2,32,6700,3.9,yes,no,no,poor,yes,yes,ckd,1,0,1,0
4,4,51,80,1,2,0,106.0,26.0,1.4,NaN,NaN,11.6,35,7300,4.6,no,no,no,good,no,no,ckd,1,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,395,55,80,1,0,0,140.0,49.0,0.5,150.0,4.9,15.7,47,6700,4.9,no,no,no,good,no,no,notckd,1,1,0,0
396,396,42,70,1,0,0,75.0,31.0,1.2,141.0,3.5,16.5,54,7800,6.2,no,no,no,good,no,no,notckd,1,1,0,0
397,397,12,80,1,0,0,100.0,26.0,0.6,137.0,4.4,15.8,49,6600,5.4,no,no,no,good,no,no,notckd,1,1,0,0
398,398,17,60,1,0,0,114.0,50.0,1.0,135.0,4.9,14.2,51,7200,5.9,no,no,no,good,no,no,notckd,1,1,0,0
399,399,58,80,1,0,0,131.0,18.0,1.1,141.0,3.5,15.8,53,6800,6.1,no,no,no,good,no,no,notckd,1,1,0,0

In [60]:
# Scale features before imputation
scaler = StandardScaler()
data_scaled = scaler.fit_transform(dataset[["ba_present"]])

# Step 2: Apply KNN Imputer
from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=3)
data_imputed = imputer.fit_transform(data_scaled)

# Step 3: Inverse scaling back to original scale
data_imputed = scaler.inverse_transform(data_imputed)

# Step 4: Convert back to DataFrame
imputed_df = pd.DataFrame(data_imputed, columns=["ba_present"])

dataset[["ba_present"]] =np.round(imputed_df).astype(int)

In [61]:
dataset[["ba_present"]].isnull().sum()

ba_present    0
dtype: int64

In [62]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 26 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              400 non-null    int64
 1   age             400 non-null    int64
 2   bp              400 non-null    int64
 3   sg              400 non-null    int64
 4   al              400 non-null    int64
 5   su              400 non-null    int64
 6   bgr             356 non-null    float64
 7   bu              381 non-null    float64
 8   sc              383 non-null    float64
 9   sod             313 non-null    float64
 10  pot             312 non-null    float64
 11  hemo            348 non-null    float64
 12  pcv             330 non-null    object
 13  wc              295 non-null    object
 14  rc              270 non-null    object
 15  htn             398 non-null    object
 16  dm              398 non-null    object
 17  cad             398 non-null    object
 18  appet           399 non-null    object
 19  pe              399 non-null    object
 20  ane             399 non-null    object
 21  classification  400 non-null    object
 22  rbc_normal      400 non-null    int64
 23  pc_normal       400 non-null    int64
 24  pcc_present     400 non-null    int64
 25  ba_present      400 non-null    int64
dtypes: float64(6), int64(10), object(10)
memory usage: 81.4+ KB

In [63]:
from sklearn.preprocessing import StandardScaler
# Scale features before imputation
scaler = StandardScaler()
data_scaled = scaler.fit_transform(dataset[["bgr"]])

# Step 2: Apply KNN Imputer
from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=3)
data_imputed = imputer.fit_transform(data_scaled)

# Step 3: Inverse scaling back to original scale
data_imputed = scaler.inverse_transform(data_imputed)

# Step 4: Convert back to DataFrame
imputed_df = pd.DataFrame(data_imputed, columns=["bgr"])

dataset[["bgr"]] =np.round(imputed_df).astype(int)

In [64]:
dataset[["bgr"]].isnull().sum()

bgr    0
dtype: int64

In [65]:
from sklearn.preprocessing import StandardScaler
# Scale features before imputation
scaler = StandardScaler()
data_scaled = scaler.fit_transform(dataset[["bu"]])

# Step 2: Apply KNN Imputer
from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=3)
data_imputed = imputer.fit_transform(data_scaled)

# Step 3: Inverse scaling back to original scale
data_imputed = scaler.inverse_transform(data_imputed)

# Step 4: Convert back to DataFrame
imputed_df = pd.DataFrame(data_imputed, columns=["bu"])

dataset[["bu"]] =np.round(imputed_df).astype(int)

In [66]:
dataset[["bu"]].isnull().sum()

bu    0
dtype: int64

In [67]:
from sklearn.preprocessing import StandardScaler
# Scale features before imputation
scaler = StandardScaler()
data_scaled = scaler.fit_transform(dataset[["sc"]])

# Step 2: Apply KNN Imputer
from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=3)
data_imputed = imputer.fit_transform(data_scaled)

# Step 3: Inverse scaling back to original scale
data_imputed = scaler.inverse_transform(data_imputed)

# Step 4: Convert back to DataFrame
imputed_df = pd.DataFrame(data_imputed, columns=["sc"])

dataset[["sc"]] =np.round(imputed_df).astype(int)

In [68]:
dataset[["sc"]].isnull().sum()

sc    0
dtype: int64

In [69]:
from sklearn.preprocessing import StandardScaler
# Scale features before imputation
scaler = StandardScaler()
data_scaled = scaler.fit_transform(dataset[["sod"]])

# Step 2: Apply KNN Imputer
from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=3)
data_imputed = imputer.fit_transform(data_scaled)

# Step 3: Inverse scaling back to original scale
data_imputed = scaler.inverse_transform(data_imputed)

# Step 4: Convert back to DataFrame
imputed_df = pd.DataFrame(data_imputed, columns=["sod"])

dataset[["sod"]] =np.round(imputed_df).astype(int)

In [70]:
dataset[["sod"]].isnull().sum()

sod    0
dtype: int64

In [71]:
from sklearn.preprocessing import StandardScaler
# Scale features before imputation
scaler = StandardScaler()
data_scaled = scaler.fit_transform(dataset[["pot"]])

# Step 2: Apply KNN Imputer
from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=3)
data_imputed = imputer.fit_transform(data_scaled)

# Step 3: Inverse scaling back to original scale
data_imputed = scaler.inverse_transform(data_imputed)

# Step 4: Convert back to DataFrame
imputed_df = pd.DataFrame(data_imputed, columns=["pot"])

dataset[["pot"]] =np.round(imputed_df).astype(int)

In [72]:
dataset[["pot"]].isnull().sum()

pot    0
dtype: int64

In [73]:
from sklearn.preprocessing import StandardScaler
# Scale features before imputation
scaler = StandardScaler()
data_scaled = scaler.fit_transform(dataset[["hemo"]])

# Step 2: Apply KNN Imputer
from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=3)
data_imputed = imputer.fit_transform(data_scaled)

# Step 3: Inverse scaling back to original scale
data_imputed = scaler.inverse_transform(data_imputed)

# Step 4: Convert back to DataFrame
imputed_df = pd.DataFrame(data_imputed, columns=["hemo"])

dataset[["hemo"]] =np.round(imputed_df).astype(int)

In [74]:
dataset[["hemo"]].isnull().sum()

hemo    0
dtype: int64

In [75]:
dataset[["pcv"]].value_counts()

pcv
41      21
52      21
48      19
44      19
40      16
43      14
42      13
45      13
32      12
33      12
36      12
28      12
50      12
34      11
37      11
30       9
29       9
46       9
35       9
31       8
24       7
39       7
26       6
38       5
51       4
53       4
47       4
49       4
54       4
25       3
27       3
22       3
19       2
23       2
20       1
15       1
\t43     1
21       1
17       1
18       1
16       1
\t?      1
14       1
9        1
Name: count, dtype: int64

In [76]:
dataset['pcv'] = dataset['pcv'].replace('\t43', 43)
dataset['pcv'] = dataset['pcv'].replace('\t?', 12)

In [77]:
dataset[["pcv"]].value_counts()

pcv
41     21
52     21
48     19
44     19
40     16
43     14
42     13
45     13
32     12
33     12
36     12
28     12
50     12
34     11
37     11
30      9
29      9
46      9
35      9
31      8
24      7
39      7
26      6
38      5
51      4
53      4
47      4
49      4
54      4
25      3
27      3
22      3
19      2
23      2
20      1
15      1
12      1
21      1
17      1
18      1
16      1
43      1
14      1
9       1
Name: count, dtype: int64

In [78]:

from sklearn.preprocessing import StandardScaler
# Scale features before imputation
scaler = StandardScaler()
data_scaled = scaler.fit_transform(dataset[["pcv"]])

# Step 2: Apply KNN Imputer

from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=3)
data_imputed = imputer.fit_transform(data_scaled)

# Step 3: Inverse scaling back to original scale
data_imputed = scaler.inverse_transform(data_imputed)

# Step 4: Convert back to DataFrame
imputed_df = pd.DataFrame(data_imputed, columns=["pcv"])

dataset[["pcv"]] =np.round(imputed_df)

In [79]:
dataset[["pcv"]].isnull().sum()

pcv    0
dtype: int64

In [80]:
display(dataset[["wc"]].value_counts())

wc
9800     11
6700     10
9200      9
7200      9
9600      9
         ..
16700     1
2200      1
2600      1
9700      1
9900      1
Name: count, Length: 92, dtype: int64

In [81]:
dataset["wc"].unique()

array(['7800', '6000', '7500', '6700', '7300', nan, '6900', '9600',
       '12100', '4500', '12200', '11000', '3800', '11400', '5300', '9200',
       '6200', '8300', '8400', '10300', '9800', '9100', '7900', '6400',
       '8600', '18900', '21600', '4300', '8500', '11300', '7200', '7700',
       '14600', '6300', '\t6200', '7100', '11800', '9400', '5500', '5800',
       '13200', '12500', '5600', '7000', '11900', '10400', '10700',
       '12700', '6800', '6500', '13600', '10200', '9000', '14900', '8200',
       '15200', '5000', '16300', '12400', '\t8400', '10500', '4200',
       '4700', '10900', '8100', '9500', '2200', '12800', '11200', '19100',
       '\t?', '12300', '16700', '2600', '26400', '8800', '7400', '4900',
       '8000', '12000', '15700', '4100', '5700', '11500', '5400', '10800',
       '9900', '5200', '5900', '9300', '9700', '5100', '6600'],
      dtype=object)

In [82]:
dataset['wc'] = dataset['wc'].replace('\t6200', 6200)
dataset['wc'] = dataset['wc'].replace('\t8400', 8400)
dataset['wc'] = dataset['wc'].replace('\t?', 3900)

In [83]:
from sklearn.preprocessing import StandardScaler
# Scale features before imputation
scaler = StandardScaler()
data_scaled = scaler.fit_transform(dataset[["wc"]])

# Step 2: Apply KNN Imputer
from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=3)
data_imputed = imputer.fit_transform(data_scaled)

# Step 3: Inverse scaling back to original scale
data_imputed = scaler.inverse_transform(data_imputed)

# Step 4: Convert back to DataFrame
imputed_df = pd.DataFrame(data_imputed, columns=["wc"])

dataset[["wc"]] =np.round(imputed_df).astype(int)

In [84]:
dataset[["wc"]].isnull().sum()

wc    0
dtype: int64

In [85]:
dataset['rc'].unique()

array(['5.2', nan, '3.9', '4.6', '4.4', '5', '4.0', '3.7', '3.8', '3.4',
       '2.6', '2.8', '4.3', '3.2', '3.6', '4', '4.1', '4.9', '2.5', '4.2',
       '4.5', '3.1', '4.7', '3.5', '6.0', '5.0', '2.1', '5.6', '2.3',
       '2.9', '2.7', '8.0', '3.3', '3.0', '3', '2.4', '4.8', '\t?', '5.4',
       '6.1', '6.2', '6.3', '5.1', '5.8', '5.5', '5.3', '6.4', '5.7',
       '5.9', '6.5'], dtype=object)

In [86]:
dataset["rc"]=dataset["rc"].replace('\t?', 5)

In [87]:
#step 1 standard scaler
from sklearn.preprocessing import StandardScaler
# Scale features before imputation
scaler = StandardScaler()
data_scaled = scaler.fit_transform(dataset[["rc"]])

# Step 2: Apply KNN Imputer
from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=3)
data_imputed = imputer.fit_transform(data_scaled)

# Step 3: Inverse scaling back to original scale
data_imputed = scaler.inverse_transform(data_imputed)


# Step 4: Convert back to DataFrame
imputed_df = pd.DataFrame(data_imputed, columns=["rc"])

dataset[["rc"]] =np.round(imputed_df).astype(int)

In [88]:
dataset[["rc"]].isnull().sum()

rc    0
dtype: int64

In [89]:
dataset['htn'].unique()

array(['yes', 'no', nan], dtype=object)

In [90]:
dataset = pd.get_dummies(dataset, columns=["htn"], drop_first=True, dummy_na=False, dtype=int)

In [91]:
dataset

,id,age,bp,sg,al,su,bgr,bu,sc,sod,pot,hemo,pcv,wc,rc,dm,cad,appet,pe,ane,classification,rbc_normal,pc_normal,pcc_present,ba_present,htn_yes
0,0,48,80,1,1,0,121,36,1,138,5,15,44.0,7800,5,yes,no,good,no,no,ckd,0,1,0,0,1
1,1,7,50,1,4,0,148,18,1,138,5,11,38.0,6000,5,no,no,good,no,no,ckd,0,1,0,0,0
2,2,62,80,1,2,3,423,53,2,138,5,10,31.0,7500,5,yes,no,poor,no,yes,ckd,1,1,0,0,0
3,3,48,70,1,4,0,117,56,4,111,2,11,32.0,6700,4,no,no,poor,yes,yes,ckd,1,0,1,0,1
4,4,51,80,1,2,0,106,26,1,138,5,12,35.0,7300,5,no,no,good,no,no,ckd,1,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,395,55,80,1,0,0,140,49,0,150,5,16,47.0,6700,5,no,no,good,no,no,notckd,1,1,0,0,0
396,396,42,70,1,0,0,75,31,1,141,4,16,54.0,7800,6,no,no,good,no,no,notckd,1,1,0,0,0
397,397,12,80,1,0,0,100,26,1,137,4,16,49.0,6600,5,no,no,good,no,no,notckd,1,1,0,0,0
398,398,17,60,1,0,0,114,50,1,135,5,14,51.0,7200,6,no,no,good,no,no,notckd,1,1,0,0,0
399,399,58,80,1,0,0,131,18,1,141,4,16,53.0,6800,6,no,no,good,no,no,notckd,1,1,0,0,0

In [92]:
#step 1 standard scaler
from sklearn.preprocessing import StandardScaler
# Scale features before imputation
scaler = StandardScaler()
data_scaled = scaler.fit_transform(dataset[["htn_yes"]])

# Step 2: Apply KNN Imputer
from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=3)
data_imputed = imputer.fit_transform(data_scaled)

# Step 3: Inverse scaling back to original scale
data_imputed = scaler.inverse_transform(data_imputed)


# Step 4: Convert back to DataFrame
imputed_df = pd.DataFrame(data_imputed, columns=["htn_yes"])

dataset[["htn_yes"]] =np.round(imputed_df).astype(int)

In [93]:
dataset[["htn_yes"]].isnull().sum()

htn_yes    0
dtype: int64

In [94]:
dataset["dm"].unique()

array(['yes', 'no', ' yes', '\tno', '\tyes', nan], dtype=object)

In [95]:
dataset["dm"]=dataset["dm"].replace('\tno', 'no')
dataset["dm"]=dataset["dm"].replace('\tyes', 'yes')
dataset["dm"]=dataset["dm"].replace(' yes', 'yes')

In [96]:
dataset = pd.get_dummies(dataset, columns=["dm"], drop_first=True, dummy_na=False, dtype=int)

In [97]:
dataset

,id,age,bp,sg,al,su,bgr,bu,sc,sod,pot,hemo,pcv,wc,rc,cad,appet,pe,ane,classification,rbc_normal,pc_normal,pcc_present,ba_present,htn_yes,dm_yes
0,0,48,80,1,1,0,121,36,1,138,5,15,44.0,7800,5,no,good,no,no,ckd,0,1,0,0,1,1
1,1,7,50,1,4,0,148,18,1,138,5,11,38.0,6000,5,no,good,no,no,ckd,0,1,0,0,0,0
2,2,62,80,1,2,3,423,53,2,138,5,10,31.0,7500,5,no,poor,no,yes,ckd,1,1,0,0,0,1
3,3,48,70,1,4,0,117,56,4,111,2,11,32.0,6700,4,no,poor,yes,yes,ckd,1,0,1,0,1,0
4,4,51,80,1,2,0,106,26,1,138,5,12,35.0,7300,5,no,good,no,no,ckd,1,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,395,55,80,1,0,0,140,49,0,150,5,16,47.0,6700,5,no,good,no,no,notckd,1,1,0,0,0,0
396,396,42,70,1,0,0,75,31,1,141,4,16,54.0,7800,6,no,good,no,no,notckd,1,1,0,0,0,0
397,397,12,80,1,0,0,100,26,1,137,4,16,49.0,6600,5,no,good,no,no,notckd,1,1,0,0,0,0
398,398,17,60,1,0,0,114,50,1,135,5,14,51.0,7200,6,no,good,no,no,notckd,1,1,0,0,0,0
399,399,58,80,1,0,0,131,18,1,141,4,16,53.0,6800,6,no,good,no,no,notckd,1,1,0,0,0,0

In [98]:
#step 1 standard scaler
from sklearn.preprocessing import StandardScaler
# Scale features before imputation
scaler = StandardScaler()
data_scaled = scaler.fit_transform(dataset[["dm_yes"]])

# Step 2: Apply KNN Imputer
from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=3)
data_imputed = imputer.fit_transform(data_scaled)

# Step 3: Inverse scaling back to original scale
data_imputed = scaler.inverse_transform(data_imputed)


# Step 4: Convert back to DataFrame
imputed_df = pd.DataFrame(data_imputed, columns=["dm_yes"])

dataset[["dm_yes"]] =np.round(imputed_df).astype(int)

In [99]:
dataset[["dm_yes"]].isnull().sum()

dm_yes    0
dtype: int64

In [100]:
dataset["cad"].unique()

array(['no', 'yes', '\tno', nan], dtype=object)

In [101]:
dataset["cad"]=dataset["cad"].replace('\tno', 'no')

In [102]:
dataset = pd.get_dummies(dataset, columns=["cad"], drop_first=True, dummy_na=False, dtype=int)

In [103]:
dataset

,id,age,bp,sg,al,su,bgr,bu,sc,sod,pot,hemo,pcv,wc,rc,appet,pe,ane,classification,rbc_normal,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes
0,0,48,80,1,1,0,121,36,1,138,5,15,44.0,7800,5,good,no,no,ckd,0,1,0,0,1,1,0
1,1,7,50,1,4,0,148,18,1,138,5,11,38.0,6000,5,good,no,no,ckd,0,1,0,0,0,0,0
2,2,62,80,1,2,3,423,53,2,138,5,10,31.0,7500,5,poor,no,yes,ckd,1,1,0,0,0,1,0
3,3,48,70,1,4,0,117,56,4,111,2,11,32.0,6700,4,poor,yes,yes,ckd,1,0,1,0,1,0,0
4,4,51,80,1,2,0,106,26,1,138,5,12,35.0,7300,5,good,no,no,ckd,1,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,395,55,80,1,0,0,140,49,0,150,5,16,47.0,6700,5,good,no,no,notckd,1,1,0,0,0,0,0
396,396,42,70,1,0,0,75,31,1,141,4,16,54.0,7800,6,good,no,no,notckd,1,1,0,0,0,0,0
397,397,12,80,1,0,0,100,26,1,137,4,16,49.0,6600,5,good,no,no,notckd,1,1,0,0,0,0,0
398,398,17,60,1,0,0,114,50,1,135,5,14,51.0,7200,6,good,no,no,notckd,1,1,0,0,0,0,0
399,399,58,80,1,0,0,131,18,1,141,4,16,53.0,6800,6,good,no,no,notckd,1,1,0,0,0,0,0

In [104]:
#step 1 standard scaler
from sklearn.preprocessing import StandardScaler
# Scale features before imputation
scaler = StandardScaler()
data_scaled = scaler.fit_transform(dataset[["cad_yes"]])

# Step 2: Apply KNN Imputer
from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=3)
data_imputed = imputer.fit_transform(data_scaled)

# Step 3: Inverse scaling back to original scale
data_imputed = scaler.inverse_transform(data_imputed)


# Step 4: Convert back to DataFrame
imputed_df = pd.DataFrame(data_imputed, columns=["cad_yes"])

dataset[["cad_yes"]] =np.round(imputed_df).astype(int)

In [105]:
dataset[["cad_yes"]].isnull().sum()

cad_yes    0
dtype: int64

In [106]:
dataset["appet"].unique()

array(['good', 'poor', nan], dtype=object)

In [107]:
dataset = pd.get_dummies(dataset, columns=["appet"], drop_first=True, dummy_na=False, dtype=int)

In [108]:
dataset

,id,age,bp,sg,al,su,bgr,bu,sc,sod,pot,hemo,pcv,wc,rc,pe,ane,classification,rbc_normal,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_poor
0,0,48,80,1,1,0,121,36,1,138,5,15,44.0,7800,5,no,no,ckd,0,1,0,0,1,1,0,0
1,1,7,50,1,4,0,148,18,1,138,5,11,38.0,6000,5,no,no,ckd,0,1,0,0,0,0,0,0
2,2,62,80,1,2,3,423,53,2,138,5,10,31.0,7500,5,no,yes,ckd,1,1,0,0,0,1,0,1
3,3,48,70,1,4,0,117,56,4,111,2,11,32.0,6700,4,yes,yes,ckd,1,0,1,0,1,0,0,1
4,4,51,80,1,2,0,106,26,1,138,5,12,35.0,7300,5,no,no,ckd,1,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,395,55,80,1,0,0,140,49,0,150,5,16,47.0,6700,5,no,no,notckd,1,1,0,0,0,0,0,0
396,396,42,70,1,0,0,75,31,1,141,4,16,54.0,7800,6,no,no,notckd,1,1,0,0,0,0,0,0
397,397,12,80,1,0,0,100,26,1,137,4,16,49.0,6600,5,no,no,notckd,1,1,0,0,0,0,0,0
398,398,17,60,1,0,0,114,50,1,135,5,14,51.0,7200,6,no,no,notckd,1,1,0,0,0,0,0,0
399,399,58,80,1,0,0,131,18,1,141,4,16,53.0,6800,6,no,no,notckd,1,1,0,0,0,0,0,0

In [109]:
#step 1 standard scaler
from sklearn.preprocessing import StandardScaler
# Scale features before imputation
scaler = StandardScaler()
data_scaled = scaler.fit_transform(dataset[["appet_poor"]])

# Step 2: Apply KNN Imputer
from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=3)
data_imputed = imputer.fit_transform(data_scaled)

# Step 3: Inverse scaling back to original scale
data_imputed = scaler.inverse_transform(data_imputed)


# Step 4: Convert back to DataFrame
imputed_df = pd.DataFrame(data_imputed, columns=["appet_poor"])

dataset[["appet_poor"]] =np.round(imputed_df).astype(int)

In [110]:
dataset[["appet_poor"]].isnull().sum()

appet_poor    0
dtype: int64

In [111]:
dataset["pe"].unique()

array(['no', 'yes', nan], dtype=object)

In [112]:
dataset = pd.get_dummies(dataset, columns=["pe"], drop_first=True, dummy_na=False, dtype=int)

In [113]:
dataset

,id,age,bp,sg,al,su,bgr,bu,sc,sod,pot,hemo,pcv,wc,rc,ane,classification,rbc_normal,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_poor,pe_yes
0,0,48,80,1,1,0,121,36,1,138,5,15,44.0,7800,5,no,ckd,0,1,0,0,1,1,0,0,0
1,1,7,50,1,4,0,148,18,1,138,5,11,38.0,6000,5,no,ckd,0,1,0,0,0,0,0,0,0
2,2,62,80,1,2,3,423,53,2,138,5,10,31.0,7500,5,yes,ckd,1,1,0,0,0,1,0,1,0
3,3,48,70,1,4,0,117,56,4,111,2,11,32.0,6700,4,yes,ckd,1,0,1,0,1,0,0,1,1
4,4,51,80,1,2,0,106,26,1,138,5,12,35.0,7300,5,no,ckd,1,1,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,395,55,80,1,0,0,140,49,0,150,5,16,47.0,6700,5,no,notckd,1,1,0,0,0,0,0,0,0
396,396,42,70,1,0,0,75,31,1,141,4,16,54.0,7800,6,no,notckd,1,1,0,0,0,0,0,0,0
397,397,12,80,1,0,0,100,26,1,137,4,16,49.0,6600,5,no,notckd,1,1,0,0,0,0,0,0,0
398,398,17,60,1,0,0,114,50,1,135,5,14,51.0,7200,6,no,notckd,1,1,0,0,0,0,0,0,0
399,399,58,80,1,0,0,131,18,1,141,4,16,53.0,6800,6,no,notckd,1,1,0,0,0,0,0,0,0

In [114]:
#step 1 standard scaler
from sklearn.preprocessing import StandardScaler
# Scale features before imputation
scaler = StandardScaler()
data_scaled = scaler.fit_transform(dataset[["pe_yes"]])

# Step 2: Apply KNN Imputer
from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=3)
data_imputed = imputer.fit_transform(data_scaled)

# Step 3: Inverse scaling back to original scale
data_imputed = scaler.inverse_transform(data_imputed)


# Step 4: Convert back to DataFrame
imputed_df = pd.DataFrame(data_imputed, columns=["pe_yes"])

dataset[["pe_yes"]] =np.round(imputed_df).astype(int)

In [115]:
dataset["ane"].unique()

array(['no', 'yes', nan], dtype=object)

In [116]:
dataset = pd.get_dummies(dataset, columns=["ane"], drop_first=True, dummy_na=False, dtype=int)

In [117]:
dataset

,id,age,bp,sg,al,su,bgr,bu,sc,sod,pot,hemo,pcv,wc,rc,classification,rbc_normal,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_poor,pe_yes,ane_yes
0,0,48,80,1,1,0,121,36,1,138,5,15,44.0,7800,5,ckd,0,1,0,0,1,1,0,0,0,0
1,1,7,50,1,4,0,148,18,1,138,5,11,38.0,6000,5,ckd,0,1,0,0,0,0,0,0,0,0
2,2,62,80,1,2,3,423,53,2,138,5,10,31.0,7500,5,ckd,1,1,0,0,0,1,0,1,0,1
3,3,48,70,1,4,0,117,56,4,111,2,11,32.0,6700,4,ckd,1,0,1,0,1,0,0,1,1,1
4,4,51,80,1,2,0,106,26,1,138,5,12,35.0,7300,5,ckd,1,1,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,395,55,80,1,0,0,140,49,0,150,5,16,47.0,6700,5,notckd,1,1,0,0,0,0,0,0,0,0
396,396,42,70,1,0,0,75,31,1,141,4,16,54.0,7800,6,notckd,1,1,0,0,0,0,0,0,0,0
397,397,12,80,1,0,0,100,26,1,137,4,16,49.0,6600,5,notckd,1,1,0,0,0,0,0,0,0,0
398,398,17,60,1,0,0,114,50,1,135,5,14,51.0,7200,6,notckd,1,1,0,0,0,0,0,0,0,0
399,399,58,80,1,0,0,131,18,1,141,4,16,53.0,6800,6,notckd,1,1,0,0,0,0,0,0,0,0

In [118]:
#step 1 standard scaler
from sklearn.preprocessing import StandardScaler
# Scale features before imputation
scaler = StandardScaler()
data_scaled = scaler.fit_transform(dataset[["ane_yes"]])

# Step 2: Apply KNN Imputer
from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=3)
data_imputed = imputer.fit_transform(data_scaled)

# Step 3: Inverse scaling back to original scale
data_imputed = scaler.inverse_transform(data_imputed)


# Step 4: Convert back to DataFrame
imputed_df = pd.DataFrame(data_imputed, columns=["ane_yes"])

dataset[["ane_yes"]] =np.round(imputed_df).astype(int)

In [119]:
dataset[["ane_yes"]].isnull().sum()

ane_yes    0
dtype: int64

In [120]:
dataset

,id,age,bp,sg,al,su,bgr,bu,sc,sod,pot,hemo,pcv,wc,rc,classification,rbc_normal,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_poor,pe_yes,ane_yes
0,0,48,80,1,1,0,121,36,1,138,5,15,44.0,7800,5,ckd,0,1,0,0,1,1,0,0,0,0
1,1,7,50,1,4,0,148,18,1,138,5,11,38.0,6000,5,ckd,0,1,0,0,0,0,0,0,0,0
2,2,62,80,1,2,3,423,53,2,138,5,10,31.0,7500,5,ckd,1,1,0,0,0,1,0,1,0,1
3,3,48,70,1,4,0,117,56,4,111,2,11,32.0,6700,4,ckd,1,0,1,0,1,0,0,1,1,1
4,4,51,80,1,2,0,106,26,1,138,5,12,35.0,7300,5,ckd,1,1,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,395,55,80,1,0,0,140,49,0,150,5,16,47.0,6700,5,notckd,1,1,0,0,0,0,0,0,0,0
396,396,42,70,1,0,0,75,31,1,141,4,16,54.0,7800,6,notckd,1,1,0,0,0,0,0,0,0,0
397,397,12,80,1,0,0,100,26,1,137,4,16,49.0,6600,5,notckd,1,1,0,0,0,0,0,0,0,0
398,398,17,60,1,0,0,114,50,1,135,5,14,51.0,7200,6,notckd,1,1,0,0,0,0,0,0,0,0
399,399,58,80,1,0,0,131,18,1,141,4,16,53.0,6800,6,notckd,1,1,0,0,0,0,0,0,0,0

In [121]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 26 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              400 non-null    int64
 1   age             400 non-null    int64
 2   bp              400 non-null    int64
 3   sg              400 non-null    int64
 4   al              400 non-null    int64
 5   su              400 non-null    int64
 6   bgr             400 non-null    int64
 7   bu              400 non-null    int64
 8   sc              400 non-null    int64
 9   sod             400 non-null    int64
 10  pot             400 non-null    int64
 11  hemo            400 non-null    int64
 12  pcv             400 non-null    float64
 13  wc              400 non-null    int64
 14  rc              400 non-null    int64
 15  classification  400 non-null    object
 16  rbc_normal      400 non-null    int64
 17  pc_normal       400 non-null    int64
 18  pcc_present     400 non-null    int64
 19  ba_present      400 non-null    int64
 20  htn_yes         400 non-null    int64
 21  dm_yes          400 non-null    int64
 22  cad_yes         400 non-null    int64
 23  appet_poor      400 non-null    int64
 24  pe_yes          400 non-null    int64
 25  ane_yes         400 non-null    int64
dtypes: float64(1), int64(24), object(1)
memory usage: 81.4+ KB

In [140]:
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression

# Separate features (X) and target (y)
X = dataset.drop('classification', axis=1)
y = dataset['classification']

# Initialize a model (Logistic Regression is a common choice for RFE)
model = LogisticRegression(solver='liblinear')

# Initialize RFE with the model and the number of features to select (you can adjust this number)
rfe = RFE(model, n_features_to_select=10) # Selecting top 10 features

# Fit RFE to the data
rfe.fit(X, y)

# Get the selected features
selected_features = X.columns[rfe.support_]

print("Selected Features by RFE:")
print(selected_features)

Selected Features by RFE:
Index(['al', 'su', 'sc', 'rc', 'rbc_normal', 'pc_normal', 'htn_yes', 'dm_yes',
       'appet_poor', 'pe_yes'],
      dtype='object')

In [141]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# Separate features (X) and target (y)
X = dataset.drop('classification', axis=1)
y = dataset['classification']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Initialize and train a Logistic Regression model
model = LogisticRegression(solver='liblinear')
model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test)

# Calculate and print the accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy}")

Accuracy: 1.0

In [135]:
dataset.to_csv("cleaned_kidney_disease.csv", index=False)